# -*- coding: utf-8 -*-
from ccxt import NotSupported
# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.base.exchange import Exchange
from ccxt.abstract.gains import ImplicitAPI
from ccxt.base.types import Bool, Int, LeverageTier, LeverageTiers, Market, Num, Order, OrderSide, OrderType, Str, Strings, Ticker, Trade, Fee
from typing import List, Any
from ccxt.base.errors import ExchangeError
from ccxt.base.errors import ArgumentsRequired
from ccxt.base.decimal_to_precision import TICK_SIZE


class gains(Exchange, ImplicitAPI):

    def describe(self):
        return self.deep_extend(super(gains, self).describe(), {
            'id': 'gains',
            'name': 'gains',
            'countries': ['EU'],
            'version': 'v1',
            'rateLimit': 10,
            'pro': False,
            'has': {
                'CORS': None,
                'spot': False,
                'margin': False,
                'swap': False,
                'future': False,
                'option': False,
                'cancelAllOrders': False,
                'cancelOrder': True,
                'cancelOrders': False,
                'closeAllPositions': False,
                'closePosition': False,
                'createOrder': True,
                'editOrder': False,
                'fetchBalance': True,
                'fetch_markets': True,
                'fetchBorrowRateHistories': False,
                'fetchBorrowRateHistory': False,
                'fetchClosedOrders': False,
                'fetchCrossBorrowRate': False,
                'fetchCrossBorrowRates': False,
                'fetchCurrencies': False,
                'fetchDepositAddress': False,
                'fetchDeposits': False,
                'fetchFundingHistory': False,
                'fetchFundingRate': False,
                'fetchFundingRateHistory': False,
                'fetchFundingRates': False,
                'fetchIndexOHLCV': False,
                'fetchIsolatedBorrowRate': False,
                'fetchIsolatedBorrowRates': False,
                'fetchLeverageTiers': True,
                'fetchMarginMode': False,
                'fetchMarkets': True,
                'fetchMarkOHLCV': False,
                'fetchMyTrades': True,
                'fetchOHLCV': True,
                'fetchOpenInterestHistory': False,
                'fetchOpenOrders': False,
                'fetchOrder': True,
                'fetchOrderBook': True,
                'fetchOrders': True,
                'fetchOrderTrades': False,
                'fetchPosition': False,
                'fetchPositionHistory': False,
                'fetchPositionMode': False,
                'fetchPositions': False,
                'fetchPositionsForSymbol': False,
                'fetchPositionsHistory': False,
                'fetchPositionsRisk': False,
                'fetchPremiumIndexOHLCV': False,
                'fetchTicker': True,
                'fetchTickers': False,
                'fetchTime': False,
                'fetchTrades': True,
                'fetchTradingFee': False,
                'fetchTradingFees': False,
                'fetchTransactionFees': False,
                'fetchTransactions': False,
                'fetchTransfer': False,
                'fetchTransfers': False,
                'fetchWithdrawal': False,
                'fetchWithdrawals': False,
                'setLeverage': True,
                'setMarginMode': False,
                'transfer': False,
                'withdraw': False,
                'ws': False,
            },
            # TODO: update self with real timeframes provided by gains if needed
            'timeframes': {
                '1m': 1,
                '5m': 5,
                '10m': 10,
                '30m': 10,
                '1h': 60,
                '2h': 120,
                '4h': 240,
                '8h': 480,
                '12h': 720,
                '1d': 24,
                '1w': 70,
                '1M': 31,
            },
            # TODO: update self with real URLs provided by gains
            'urls': {
                'logo': 'https://some-logo.jpg',
                'api': {
                    'public': 'http://localhost:8000',
                    'private': 'http://localhost:8000',
                },
                'www': 'https://gains.com/',
                'doc': [
                    'https://gains.com/gains-offical-api-docs',
                ],
                'fees': 'https://gains.com/fees',
            },
            # TODO: update self with real credentials keys provided by gains
            'requiredCredentials': {},
            'api': {
                'public': {
                    'get': [
                        'markets',
                        'ohlcv',
                        'ticker',
                        'trades',
                    ],
                },
                'private': {
                    'get': [
                        'orders',
                        'order',
                        'balance',
                        'leverage_tiers',
                    ],
                    'post': [
                        'order',
                        'leverage',
                    ],
                    'delete': [
                        'order',
                    ],
                },
            },
            # TODO: update self with real fees provided by gains
            'fees': {
            },
            'options': {
            },
            'precisionMode': TICK_SIZE,
            # TODO: update self with real exceptions provided by gains
            'exceptions': {},
            'commonCurrencies': {
            },
        })

    def fetch_markets(self, params={}) -> List[Market]:
        """
        retrieves data on all markets for gains
        :see: TODO add a link to the relevant part of the exchange API documentation
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict[]: an array of objects representing market data
        """
        response = self.publicGetMarkets(params)
        # [
        #     {
        #         "id": "BTC/USDT",
        #         "symbol": "BTC/USDT",
        #         "base": "BTC",
        #         "quote": "USDT",
        #         "baseId": "btc",
        #         "quoteId": "usdt"
        #     },
        #     {
        #         "id": "ETH/USDT",
        #         "symbol": "ETH/USDT",
        #         "base": "ETH",
        #         "quote": "USDT",
        #         "baseId": "eth",
        #         "quoteId": "usdt"
        #     }
        # ]
        return self.parse_markets(response)

    def parse_markets(self, markets: list) -> List[Market]:
        result = []
        for i in range(0, len(markets)):
            result.append(self.parse_market(markets[i]))
        return result

    def parse_market(self, market: dict) -> Market:
        # Market structure
        # {
        #     'id':      'btcusd',      // string literal for referencing within an exchange
        #     'symbol':  'BTC/USD',     // uppercase string literal of a pair of currencies
        #     'base':    'BTC',         // uppercase string, unified base currency code, 3 or more letters
        #     'quote':   'USD',         // uppercase string, unified quote currency code, 3 or more letters
        #     'baseId':  'btc',         // any string, exchange-specific base currency id
        #     'quoteId': 'usd',         // any string, exchange-specific quote currency id
        #     'active':   true,         // boolean, market status
        #     'type':    'spot',        // spot for spot, future for expiry futures, swap for perpetual swaps, 'option' for options
        #     'spot':     true,         // whether the market is a spot market
        #     'margin':   true,         // whether the market is a margin market
        #     'future':   false,        // whether the market is a expiring future
        #     'swap':     false,        // whether the market is a perpetual swap
        #     'option':   false,        // whether the market is an option contract
        #     'contract': false,        // whether the market is a future, a perpetual swap, or an option
        #     'settle':   'USDT',       // the unified currency code that the contract will settle in, only set if `contract` is true
        #     'settleId': 'usdt',       // the currencyId of that the contract will settle in, only set if `contract` is true
        #     'contractSize': 1,        // the size of one contract, only used if `contract` is true
        #     'linear':   true,         // the contract is a linear contract (settled in quote currency)
        #     'inverse':  false,        // the contract is an inverse contract (settled in base currency)
        #     'expiry':  1641370465121, // the unix expiry timestamp in milliseconds, undefined for everything except market['type'] `future`
        #     'expiryDatetime': '2022-03-26T00:00:00.000Z', // The datetime contract will in iso8601 format
        #     'strike': 4000,           // price at which a put or call option can be exercised
        #     'optionType': 'call',     // call or put string, call option represents an option with the right to buy and put an option with the right to sell
        #     // note, 'taker' and 'maker' compose extended data for markets, however it might be better to use `fetchTradingFees` for more accuracy
        #     'taker':    0.002,        // taker fee rate, 0.002 = 0.2%
        #     'maker':    0.0016,       // maker fee rate, 0.0016 = 0.16%
        #     'percentage': true,       // whether the taker and maker fee rate is a multiplier or a fixed flat amount
        #     'tierBased': false,       // whether the fee depends on your trading tier (your trading volume)
        #     'feeSide': 'get',         // string literal can be 'get', 'give', 'base', 'quote', 'other'
        #     'precision': {            // number of decimal digits "after the dot"
        #         'price': 8,           // integer or float for TICK_SIZE roundingMode, might be missing if not supplied by the exchange
        #         'amount': 8,          // integer, might be missing if not supplied by the exchange
        #         'cost': 8,            // integer, very few exchanges actually have it
        #     },
        #     'limits': {               // value limits when placing orders on this market
        #         'amount': {
        #             'min': 0.01,      // order amount should be > min
        #             'max': 1000,      // order amount should be < max
        #         },
        #         'price': { ... },     // same min/max limits for the price of the order
        #         'cost':  { ... },     // same limits for order cost = price * amount
        #         'leverage': { ... },  // same min/max limits for the leverage of the order
        #     },
        #     'marginModes': {
        #         'cross': false,       // whether pair supports cross-margin trading
        #         'isolated': false,    // whether pair supports isolated-margin trading
        #     },
        #     'info':      { ... },     // the original unparsed market info from the exchange
        # }
        precision = self.safe_value(market, 'precision', {})
        limits = self.safe_dict(market, 'limits', {})
        limit_amount = self.safe_dict(limits, 'amount', {})
        limit_price = self.safe_dict(limits, 'price', {})
        limit_cost = self.safe_dict(limits, 'cost', {})
        limit_leverage = self.safe_dict(limits, 'leverage', {})
        return  {
            'id': self.safe_string(market, 'id'),
            'symbol': self.safe_string(market, 'symbol'),
            'base': self.safe_string(market, 'base'),
            'baseId': self.safe_string(market, 'baseId'),
            'quote': self.safe_string(market, 'quote'),
            'quoteId': self.safe_string(market, 'quoteId'),
            'active': self.safe_value(market, 'active', True),
            'type': self.safe_string(market, 'type'),
            'spot': self.safe_string(market, 'type') == 'spot',
            'margin': self.safe_string(market, 'type') == 'margin',
            'future': self.safe_string(market, 'type') == 'future',
            'swap': self.safe_string(market, 'type') == 'swap',
            'option': self.safe_string(market, 'type') == 'option',
            'contract': self.safe_string(market, 'type') in ('option', 'future', 'swap'),
            'settle': None,
            'settleId': None,
            'contractSize': None,
            'linear': True,
            'inverse': None,
            'expiry': None,
            'expiryDatetime': None,
            'strike': None,
            'optionType': None,
            'taker': self.safe_float(market, 'taker'),
            'maker': self.safe_float(market, 'maker'),
            'percentage': self.safe_bool(market, 'percentage', False),
            'tierBased': self.safe_bool(market, 'tierBased', False),
            'feeSide': 'quote',
            'precision': {
                'price': self.safe_integer(precision, 'price'),
                'amount': self.safe_integer(precision, 'amount'),
                'cost': self.safe_integer(precision, 'cost')
            },
            'limits': {
                'amount' : {
                    'min': self.safe_number(limit_amount, 'min'),
                    'max': self.safe_number(limit_amount, 'max'),
                },
                'price': {
                    'min': self.safe_number(limit_price, 'min'),
                    'max': self.safe_number(limit_price, 'max'),
                },
                'cost': {
                    'min': self.safe_number(limit_cost, 'min'),
                    'max': self.safe_number(limit_cost, 'max'),
                },
                'leverage': {
                    'min': self.safe_number(limit_leverage, 'min'),
                    'max': self.safe_number(limit_leverage, 'max'),
                }
            },
            'marginModes': {
                'cross': False,
                'isolated': False,
            },
            'info': market,
        }

    def parse_orders(self, orders: list, market: Market = None, since: Int = None, limit: Int = None, params={}) -> List[Order]:
        result = []
        for i in range(0, len(orders)):
            result.append(self.parse_order(orders[i]))
        return result

    def parse_order(self, order: dict, market: Market = None) -> Order:
        # Order structure:
        # {
        #     'id':                '12345-67890:09876/54321', // string
        #     'clientOrderId':     'abcdef-ghijklmnop-qrstuvwxyz', // a user-defined clientOrderId, if any
        #     'datetime':          '2017-08-17 12:42:48.000', // ISO8601 datetime of 'timestamp' with milliseconds
        #     'timestamp':          1502962946216, // order placing/opening Unix timestamp in milliseconds
        #     'lastTradeTimestamp': 1502962956216, // Unix timestamp of the most recent trade on this order
        #     'status':      'open',        // 'open', 'closed', 'canceled', 'expired', 'rejected'
        #     'symbol':      'ETH/BTC',     // symbol
        #     'type':        'limit',       // 'market', 'limit'
        #     'timeInForce': 'GTC',         // 'GTC', 'IOC', 'FOK', 'PO'
        #     'side':        'buy',         // 'buy', 'sell'
        #     'price':        0.06917684,   // float price in quote currency (may be empty for market orders)
        #     'average':      0.06917684,   // float average filling price
        #     'amount':       1.5,          // ordered amount of base currency
        #     'filled':       1.1,          // filled amount of base currency
        #     'remaining':    0.4,          // remaining amount to fill
        #     'cost':         0.076094524,  // 'filled' * 'price' (filling price used where available)
        #     'trades':     [ ... ],        // a list of order trades/executions
        #     'fee': {                      // fee info, if available
        #         'currency': 'BTC',        // which currency the fee is (usually quote)
        #         'cost': 0.0009,           // the fee amount in that currency
        #         'rate': 0.002,            // the fee rate (if available)
        #     },
        #     'info': { ... },              // the original unparsed order structure as is
        # }
        timestamp: Int = self.safe_integer(order, 'timestamp', None)
        # TODO try to use self.safe_order
        return {
            'id': self.safe_string(order, 'id'),
            'clientOrderId': self.safe_string(order, 'clientOrderId', None),
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'lastTradeTimestamp': self.safe_integer(order, 'lastTradeTimestamp', None),
            'lastUpdateTimestamp': self.safe_integer(order, 'lastUpdated', None),
            'symbol': self.safe_string(order, 'symbol', None),
            'type': self.safe_string(order, 'type', None),
            'timeInForce': self.safe_string(order, 'timeInForce', None),
            'postOnly': None,
            'side': self.safe_string(order, 'side', None),
            'price': self.safe_float(order, 'price', None),
            'stopPrice': None,
            'amount': self.safe_float(order, 'amount', None),
            'cost': self.safe_float(order, 'cost', None),
            'average': self.safe_float(order, 'average', None),
            'filled': self.safe_float(order, 'filled', None),
            'remaining': self.safe_float(order, 'remaining', None),
            'status': self.safe_string(order, 'status', None),
            'fee': self.parse_fee(order),
            'trades': self.parse_trades(self.safe_list(order, 'trades', [])),
            'info': order,
        }

    def fetch_order(self, id: str, symbol: Str = None, params={}) -> Order:
        """
        fetches information on an order made by the user
        :see: TODO add a link to the relevant part of the exchange API documentation
        :param str id: the order id
        :param str symbol: unified symbol of the market the order was made in
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: An `order structure <https://docs.ccxt.com/#/?id=order-structure>`
        """
        request: dict = {
            'id': id,
            'pair': symbol,
        }
        response = self.privateGetOrder(self.extend(request, params))
        # {
        #     "id": "140",
        #     "clientOrderId": "49e0b476-f279-4a28-b425-0c0d19a4d4b8",
        #     "tradeId": "74",
        #     "datetime": "2025-03-06 14:21:24.000",
        #     "timestamp": 1741270884,
        #     "lastTradeTimestamp": 1741270886,
        #     "status": "CANCELED",
        #     "symbol": "ETH/USD",
        #     "type": "MARKET",
        #     "timeInForce": "GTC",
        #     "side": "BUY",
        #     "price": "2251.87900000",
        #     "average": "2251.87900000",
        #     "amount": "0.01000000",
        #     "filled": "0.01000000",
        #     "remaining": "0.00000000",
        #     "cost": "20.47162700",
        #     "leverage": "1.10",
        #     "blockNumber": 129903054,
        #     "txHash": "0x63668ea93e0742928abfc66a8c77921026a8967255c520b79277390144c42fe9",
        #     "lastUpdated": "2025-03-06T14:22:40.848Z",
        #     "trades": [
        #         {
        #             "id": "74",
        #             "timestamp": "1741270886",
        #             "datetime": "2025-03-06 14:21:26.000",
        #             "symbol": "ETH/USD",
        #             "order": "140",
        #             "isOpen": false,
        #             "type": "MARKET",
        #             "side": "BUY",
        #             "takerOrMaker": "TAKER",
        #             "price": "22523323263900.00000000",
        #             "amount": "0.00000000",
        #             "cost": "0.00000000",
        #             "lastUpdated": "2025-03-06T14:22:40.835Z",
        #             "blockNumber": 129903061,
        #             "txHash": "0x68c6fdca6bf760d11a36d8ac391a97e779fb4d721f0b8e83b159772da703c02e"
        #         }
        #     ]
        # },
        return self.parse_order(response)

    def fetch_orders(self, symbol: Str = None, since: Int = None, limit: Int = None, params={}) -> List[Order]:
        """
        fetches information on multiple orders made by the user
        :see: TODO add a link to the relevant part of the exchange API documentation
        :param str symbol: unified market symbol of the market orders were made in
        :param int [since]: the earliest time in ms to fetch orders for
        :param int [limit]: the maximum number of order structures to retrieve
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns Order[]: a list of `order structures <https://docs.ccxt.com/#/?id=order-structure>`
        """
        if symbol is None:
            raise ArgumentsRequired(self.id + ' fetchOrders() requires a symbol argument')
        request: dict = {
            'symbol': symbol,
        }
        if since is not None:
            request['since'] = since
        if limit is not None:
            request['limit'] = limit
        response = self.privateGetOrders(self.extend(request, params))
        # [
        #     {
        #         "id": "140",
        #         "clientOrderId": "49e0b476-f279-4a28-b425-0c0d19a4d4b8",
        #         "tradeId": "74",
        #         "datetime": "2025-03-06 14:21:24.000",
        #         "timestamp": 1741270884,
        #         "lastTradeTimestamp": 1741270886,
        #         "status": "CANCELED",
        #         "symbol": "ETH/USD",
        #         "type": "MARKET",
        #         "timeInForce": "GTC",
        #         "side": "BUY",
        #         "price": "2251.87900000",
        #         "average": "2251.87900000",
        #         "amount": "0.01000000",
        #         "filled": "0.01000000",
        #         "remaining": "0.00000000",
        #         "cost": "20.47162700",
        #         "leverage": "1.10",
        #         "blockNumber": 129903054,
        #         "txHash": "0x63668ea93e0742928abfc66a8c77921026a8967255c520b79277390144c42fe9",
        #         "lastUpdated": "2025-03-06T14:22:40.848Z",
        #         "trades": [
        #             {
        #                 "id": "74",
        #                 "timestamp": "1741270886",
        #                 "datetime": "2025-03-06 14:21:26.000",
        #                 "symbol": "ETH/USD",
        #                 "order": "140",
        #                 "isOpen": false,
        #                 "type": "MARKET",
        #                 "side": "BUY",
        #                 "takerOrMaker": "TAKER",
        #                 "price": "22523323263900.00000000",
        #                 "amount": "0.00000000",
        #                 "cost": "0.00000000",
        #                 "lastUpdated": "2025-03-06T14:22:40.835Z",
        #                 "blockNumber": 129903061,
        #                 "txHash": "0x68c6fdca6bf760d11a36d8ac391a97e779fb4d721f0b8e83b159772da703c02e"
        #             }
        #         ]
        #     }
        # ]
        return self.parse_orders(response)

    def create_order(self, symbol: str, type: OrderType, side: OrderSide, amount: float, price: Num = None, params={}) -> Order:
        """
        create a trade order
        :see: TODO add a link to the relevant part of the exchange API documentation
        :param str symbol: unified symbol of the market to create an order in
        :param str type: 'market' or 'limit'
        :param str side: 'buy' or 'sell'
        :param float amount: how much of currency you want to trade in units of base currency
        :param float [price]: the price at which the order is to be fulfilled, in units of the quote currency, ignored in market orders
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: an `order structure <https://docs.ccxt.com/#/?id=order-structure>`
        """

        request: dict = {
            'pair': symbol,
            'type': type,
            'side': side,
            'amount': amount,
        }
        if type != 'market':
            raise NotSupported(self.id + ' createOrder() supports market orders only')
        if side != 'buy' and side != 'sell':
            raise NotSupported(self.id + ' createOrder() side must be buy or sell')
        response = self.privatePostOrder(self.extend(request, params))
        # {
        #     "id": "147",
        #     "tradeId": null,
        #     "datetime": "2025-03-10 17:49:28.000",
        #     "timestamp": 1741628968,
        #     "lastTradeTimestamp": null,
        #     "symbol": "ETH/USD",
        #     "price": 1918.099,
        #     "amount": 0.01,
        #     "average": 1918.099,
        #     "filled": 0.01,
        #     "remaining": 0,
        #     "cost": 17.437264,
        #     "leverage": 1.1,
        #     "txHash": "0x4884d0164f43ae7943a27ef4bc258081a6f0573702fed7d6118383aa8f5c8a5a",
        #     "blockNumber": 131140814
        # }
        return self.parse_order(response)

    def cancel_order(self, id: str, symbol: Str = None, params={}) -> Order:
        """
        cancels an open order
        :see: TODO add a link to the relevant part of the exchange API documentation
        :param str id: order id
        :param str symbol: unified symbol of the market the order was made in
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: An `order structure <https://docs.ccxt.com/#/?id=order-structure>`
        """
        request: dict = {
            'id': id,
        }
        response = self.privateDeleteOrder(self.extend(request, params))
        # {
        #     "id": "147",
        #     "clientOrderId": "385036fa-474e-4df1-a448-6b4a1faf6788",
        #     "tradeId": "79",
        #     "datetime": "2025-03-10 17:49:28.000",
        #     "timestamp": 1741628968,
        #     "lastTradeTimestamp": 1741628969,
        #     "status": "EXECUTED",
        #     "symbol": "ETH/USD",
        #     "type": "MARKET",
        #     "timeInForce": "GTC",
        #     "side": "BUY",
        #     "price": "1918.09900000",
        #     "average": "1918.09900000",
        #     "amount": "0.01000000",
        #     "filled": "0.01000000",
        #     "remaining": "0.00000000",
        #     "cost": "17.43726400",
        #     "leverage": "1.10",
        #     "blockNumber": 131140814,
        #     "txHash": "0x4884d0164f43ae7943a27ef4bc258081a6f0573702fed7d6118383aa8f5c8a5a",
        #     "lastUpdated": "2025-03-10T17:49:29.618Z",
        #     "trades": [
        #         {
        #             "id": "79",
        #             "timestamp": "1741628969",
        #             "datetime": "2025-03-10 17:49:29.000",
        #             "symbol": "ETH/USD",
        #             "order": "147",
        #             "isOpen": true,
        #             "type": "MARKET",
        #             "side": "BUY",
        #             "takerOrMaker": "TAKER",
        #             "price": "19185032239200.00000000",
        #             "amount": "0.00000000",
        #             "cost": "0.00000000",
        #             "lastUpdated": "2025-03-10T17:49:29.609Z",
        #             "blockNumber": 131140817,
        #             "txHash": "0xf0cb7aa00f5172b7cd7ad57c85f4af2ac66362542fc7e6b460863065474c4377"
        #         }
        #     ]
        # }
        return self.parse_order(response)

    def parse_balance(self, balance) -> dict:
        # Balance structure:
        # {
        #     'info':  { ... },                       // the original untouched non-parsed reply with details
        #     'timestamp': 1499280391811,             // Unix Timestamp in milliseconds (seconds * 1000)
        #     'datetime': '2017-07-05T18:47:14.692Z', // ISO8601 datetime string with milliseconds
        #     'free':  {                              // money, available for trading, by currency
        #         'BTC': 321.00,                      // floats...
        #         'USD': 123.00,
        #         ...
        #     },
        #     'used':  { ... },                       // money on hold, locked, frozen, or pending, by currency
        #     'total': { ... },                       // total (free + used), by currency
        #     'debt': { ... },                        // debt, by currency
        # }
        #
        timestamp = self.safe_integer(balance, 'timestamp')
        # TODO try to use self.safe_balance
        return {
            'info': balance,
            'timestamp': self.safe_integer(balance, 'timestamp'),
            'datetime': self.iso8601(timestamp),
            'free': self.safe_dict(balance, 'free', {}),
            'used': self.safe_dict(balance, 'used', {}),
            'total': self.safe_dict(balance, 'total', {}),
            'debt': self.safe_dict(balance, 'debt', {}),
        }

    def fetch_balance(self, params={}) -> dict:
        """
        query for balance and get the amount of funds available for trading or funds locked in orders
        :see: TODO add a link to the relevant part of the exchange API documentation
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: a `balance structure <https://docs.ccxt.com/#/?id=balance-structure>`
        """
        response = self.privateGetBalance(params)
        # {
        #     "timestamp": 1741799738711,
        #     "free": {
        #         "GNS_DAI": 10000,
        #         "WETH": 0,
        #         "GNS_USDC": 39442.730502,
        #         "GNS": 0,
        #         "gas": 0.38594655468021
        #     },
        #     "used": {
        #         "GNS_USDC": 0,
        #         "GNS_DAI": 0,
        #         "WETH": 0,
        #         "GNS": 0
        #     },
        #     "total": {
        #         "GNS_DAI": 10000,
        #         "WETH": 0,
        #         "GNS_USDC": 39442.730502,
        #         "GNS": 0
        #     },
        #     "debt": {
        #         "GNS_DAI": 0,
        #         "WETH": 0,
        #         "GNS_USDC": 0,
        #         "GNS": 0
        #     }
        # }
        return self.parse_balance(response)

    def parse_ohlcvs(self, ohlcvs: List[object], market: Any = None, timeframe: str = '1m', since: Int = None, limit: Int = None, tail: Bool = False):
        results = []
        for i in range(0, len(ohlcvs)):
            results.append(self.parse_ohlcv(ohlcvs[i]))
        return results

    def parse_ohlcv(self, ohlcv, market: Market = None) -> list:
        # OHLCV structure:
        # [
        #     [
        #         1504541580000, // UTC timestamp in milliseconds, integer
        #         4235.4,        // (O)pen price, float
        #         4240.6,        // (H)ighest price, float
        #         4230.0,        // (L)owest price, float
        #         4230.7,        // (C)losing price, float
        #         37.72941911    // (V)olume float (usually in terms of the base currency, the exchanges docstring may list whether quote or base units are used)
        #     ],
        #     ...
        # ]
        if isinstance(ohlcv, list):
            return [
                self.safe_integer(ohlcv, 0),  # timestamp
                self.safe_number(ohlcv, 1),   # open
                self.safe_number(ohlcv, 2),   # high
                self.safe_number(ohlcv, 3),   # low
                self.safe_number(ohlcv, 4),   # close
                self.safe_number(ohlcv, 5),   # volume
            ]
        return ohlcv

    def fetch_ohlcv(self, symbol: str, timeframe='1m', since: Int = None, limit: Int = None, params={}) -> List[list]:
        """
        fetches historical candlestick data containing the open, high, low, and close price, and the volume of a market
        :see: TODO add a link to the relevant part of the exchange API documentation
        :param str symbol: unified symbol of the market to fetch OHLCV data for
        :param str timeframe: the length of time each candle represents
        :param int [since]: timestamp in ms of the earliest candle to fetch
        :param int [limit]: the maximum amount of candles to fetch
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns int[][]: A list of candles ordered, open, high, low, close, volume
        """
        request: dict = {
            'pair': symbol,
            'timeframe': timeframe,
        }
        if limit is not None:
            request['limit'] = limit
        if since is not None:
            request['since'] = since
        response = self.publicGetOhlcv(self.extend(request, params))
        # [
        #     [
        #         1741860840021,
        #         1892.5469,
        #         1894.94,
        #         1892.5469,
        #         1893.8924,
        #         0
        #     ],
        #     [
        #         1741860780007,
        #         1890.9524,
        #         1892.719,
        #         1890.9524,
        #         1892.5469,
        #         0
        #     ],
        # ...
        # ]
        return self.parse_ohlcvs(response)

    def parse_ticker(self, ticker: dict, market: Market = None) -> Ticker:
        # Ticker structure:
        # {
        #     'symbol':        string symbol of the market ('BTC/USD', 'ETH/BTC', ...)
        #     'info':        { the original non-modified unparsed reply from exchange API },
        #     'timestamp':     int (64-bit Unix Timestamp in milliseconds since Epoch 1 Jan 1970)
        #     'datetime':      ISO8601 datetime string with milliseconds
        #     'high':          float, // highest price
        #     'low':           float, // lowest price
        #     'bid':           float, // current best bid (buy) price
        #     'bidVolume':     float, // current best bid (buy) amount (may be missing or undefined)
        #     'ask':           float, // current best ask (sell) price
        #     'askVolume':     float, // current best ask (sell) amount (may be missing or undefined)
        #     'vwap':          float, // volume weighed average price
        #     'open':          float, // opening price
        #     'close':         float, // price of last trade (closing price for current period)
        #     'last':          float, // same as `close`, duplicated for convenience
        #     'previousClose': float, // closing price for the previous period
        #     'change':        float, // absolute change, `last - open`
        #     'percentage':    float, // relative change, `(change/open) * 100`
        #     'average':       float, // average price, `(last + open) / 2`
        #     'baseVolume':    float, // volume of base currency traded for last 24 hours
        #     'quoteVolume':   float, // volume of quote currency traded for last 24 hours
        # }

        # TODO try to use self.safe_ticker
        timestamp = self.safe_integer(ticker, 'timestamp')
        return {
            'symbol': self.safe_string(ticker, 'symbol'),
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'high': self.safe_number(ticker, 'high'),
            'low': self.safe_number(ticker, 'low'),
            'bid': self.safe_number(ticker, 'bid'),
            'bidVolume': self.safe_number(ticker, 'bid_volume'),
            'ask': self.safe_number(ticker, 'ask'),
            'askVolume': self.safe_number(ticker, 'askVolume'),
            'vwap': self.safe_number(ticker, 'vwap'),
            'open': self.safe_number(ticker, 'open'),
            'close': self.safe_number(ticker, 'close'),
            'last': self.safe_number(ticker, 'last'),
            'previousClose': self.safe_number(ticker, 'previousClose'),
            'change': self.safe_number(ticker, 'change'),
            'percentage': self.safe_number(ticker, 'percentage'),
            'average': self.safe_number(ticker, 'average'),
            'baseVolume': self.safe_number(ticker, 'baseVolume'),
            'quoteVolume': self.safe_number(ticker, 'quoteVolume'),
            'info': ticker,
        }

    def fetch_ticker(self, symbol: str, params={}) -> Ticker:
        """
        fetches a price ticker, a statistical calculation with the information calculated over the past 24 hours for a specific market
        :see: TODO add a link to the relevant part of the exchange API documentation
        :param str symbol: unified symbol of the market to fetch the ticker for
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: a `ticker structure <https://docs.ccxt.com/#/?id=ticker-structure>`
        """
        request: dict = {
            'pair': symbol,
        }
        response = self.publicGetTicker(self.extend(request, params))
        # {
        #     "symbol": "ETH/USD",
        #     "timestamp": 1742920560018,
        #     "datetime": "2025-03-25T16:36:00.018Z",
        #     "high": 2063.3282,
        #     "low": 2062.674,
        #     "bid": 2060.8252119000003,
        #     "bidVolume": 12.5,
        #     "ask": 2064.9509881,
        #     "askVolume": 8.3,
        #     "vwap": 0,
        #     "open": 2063.09,
        #     "close": 2062.8881,
        #     "last": 2062.8881,
        #     "previousClose": 2069.7879,
        #     "change": -0.20190000000002328,
        #     "percentage": -0.009786291436632589,
        #     "average": 2062.98905,
        #     "baseVolume": 0,
        #     "quoteVolume": 0
        # }
        return self.parse_ticker(response)

    def parse_leverage_tiers(self, response: Any, symbols: List[str] = None, marketIdKey=None) -> LeverageTiers:
        results = {}
        for symbol, tiers in response.items():
            results[symbol] = self.parse_market_leverage_tiers(tiers)
        return results

    def parse_market_leverage_tiers(self, info, market: Market = None) -> List[LeverageTier]:
        # Leverage tiers structure
        # [
        #     {
        #         "tier": 1,                       // tier index
        #         "symbol": "BTC/USDT",            // the market symbol that the leverage tier applies to
        #         "currency": "USDT",              // the currency that minNotional and maxNotional are in
        #         "minNotional": 0,                // the lowest amount of this tier // stake = 0.0
        #         "maxNotional": 10000,            // the highest amount of this tier // max stake amount at 75x leverage = 133.33333333333334
        #         "maintenanceMarginRate": 0.0065, // maintenance margin rate
        #         "maxLeverage": 75,               // max available leverage for this market when the value of the trade is > minNotional and < maxNotional
        #         "info": { ... }                  // Response from exchange
        #     },
        #     {
        #         "tier": 2,
        #         "symbol": "BTC/USDT",
        #         "currency": "USDT",
        #         "minNotional": 10000,            // min stake amount at 50x leverage = 200.0
        #         "maxNotional": 50000,            // max stake amount at 50x leverage = 1000.0
        #         "maintenanceMarginRate": 0.01,
        #         "maxLeverage": 50,
        #         "info": { ... },
        #     },
        #     ...
        # ]
        results = []
        for j in range(0, len(info)):
            leverageTier = info[j]
            results.append({
                'tier': self.safe_number(leverageTier, 'tier'),
                'currency': self.safe_string(leverageTier, 'notionalCurrency'),
                'minNotional': self.safe_number(leverageTier, 'minNotional'),
                'maxNotional': self.safe_number(leverageTier, 'maxNotional'),
                'maintenanceMarginRate': self.safe_number(leverageTier, 'maintenanceMarginRate'),
                'maxLeverage': self.safe_number(leverageTier, 'maxLeverage'),
                'info': leverageTier,
            })
        return results

    def fetch_leverage_tiers(self, symbols: Strings = None, params={}) -> LeverageTiers:
        """
        :see: TODO add a link to the relevant part of the exchange API documentation
        retrieve information on the maximum leverage, and maintenance margin for trades of varying trade sizes
        :param str[]|None symbols: list of unified market symbols
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: a dictionary of `leverage tiers structures <https://docs.ccxt.com/#/?id=leverage-tiers-structure>`, indexed by market symbols
        """
        request: dict = {
            'symbols': symbols,
        }
        response = self.privateGetLeverageTiers(self.extend(request, params))
        # {
        #     "ETH/USD": [
        #         {
        #             "tier": 1,
        #             "notionalCurrency": "USD",
        #             "minNotional": 1250,
        #             "maxNotional": 100,
        #             "maintenanceMarginRate": 0.01,
        #             "maxLeverage": 100
        #         }
        #     ]
        # }
        return self.parse_leverage_tiers(response)

    def parse_leverage(self, leverage: dict, market: Market = None) -> dict:
        # Leverage structure
        # {
        #     "info": { ... }             // response from the exchange
        #     "symbol": "BTC/USDT:USDT",  // unified market symbol
        #     "marginMode": "cross",      // the margin mode either cross or isolated
        #     "longLeverage": 100,        // the set leverage for a long position
        #     "shortLeverage": 75,        // the set leverage for a short position
        # }
        return {
            "info": leverage,
            "symbol": self.safe_string(leverage, 'symbol'),
            "marginMode": self.safe_string(leverage, 'marginMode'),
            "longLeverage": self.safe_number(leverage, 'longLeverage'),
            "shortLeverage": self.safe_number(leverage, 'shortLeverage'),
        }

    def set_leverage(self, leverage: Int, symbol: Str = None, params={}) -> dict:
        """
        set the level of leverage for a market
        :see: TODO add a link to the relevant part of the exchange API documentation
        :param float leverage: the rate of leverage
        :param str symbol: unified market symbol
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: response from the exchange
        """
        if symbol is None:
            raise ArgumentsRequired(self.id + ' setLeverage() requires a symbol argument')

        request: dict = {
            'pair': symbol,
            'long_leverage': leverage,
            'short_leverage': leverage,
        }
        response = self.privatePostLeverage(self.extend(request, params))
        # {
        #     "symbol": "ETH/USD",
        #     "pairIndex": 1,
        #     "longLeverage": 2,
        #     "shortLeverage": 2,
        #     "lastUpdated": "2025-03-13T11:56:42.637Z"
        # }
        return self.parse_leverage(response)

    def parse_fee(self, container: dict) -> Fee:
        # Fee structure
        # {
        #     'currency': 'BTC', // the unified fee currency code
        #     'rate': percentage, // the fee rate, 0.05% = 0.0005, 1% = 0.01, ...
        #     'cost': feePaid, // the fee cost (amount * fee rate)
        # }

        fee_cost = sum(float(f['cost']) for f in container['fees']) if 'fees' in container else float(container['fee']['cost'])
        container_cost = float(container['cost'])
        fee = {
            'currency': 'USDC',
            'rate': fee_cost / container_cost if container_cost else None,
            'cost': fee_cost if container_cost else None,
        }
        return fee

    def parsed_fee_and_fees(self, container):
        fee_total = self.parse_fee(container)
        fees_separate = []
        for fee in self.safe_list(container, 'fees', []):
            fee_container = {'cost': container['cost'], 'fee': {'cost': fee['cost']}}
            fees_separate.append(self.parse_fee(fee_container))
        return fee_total, fees_separate

    def parse_trades(self, trades: list, market: Market = None, since: Int = None, limit: Int = None, params={}) -> List[Trade]:
        result = []
        for i in range(0, len(trades)):
            result.append(self.parse_trade(trades[i]))
        return result

    def parse_trade(self, trade: dict, market: Market = None) -> Trade:
        # Trade structure:
        # {
        #     'info':         { ... },                    // the original decoded JSON as is
        #     'id':           '12345-67890:09876/54321',  // string trade id
        #     'timestamp':    1502962946216,              // Unix timestamp in milliseconds
        #     'datetime':     '2017-08-17 12:42:48.000',  // ISO8601 datetime with milliseconds
        #     'symbol':       'ETH/BTC',                  // symbol
        #     'order':        '12345-67890:09876/54321',  // string order id or undefined/None/null
        #     'type':         'limit',                    // order type, 'market', 'limit' or undefined/None/null
        #     'side':         'buy',                      // direction of the trade, 'buy' or 'sell'
        #     'takerOrMaker': 'taker',                    // string, 'taker' or 'maker'
        #     'price':        0.06917684,                 // float price in quote currency
        #     'amount':       1.5,                        // amount of base currency
        #     'cost':         0.10376526,                 // total cost, `price * amount`,
        #     'fee':          {                           // provided by exchange or calculated by ccxt
        #         'cost':  0.0015,                        // float
        #         'currency': 'ETH',                      // usually base currency for buys, quote currency for sells
        #         'rate': 0.002,                          // the fee rate (if available)
        #     },
        #     'fees': [                                   // an array of fees if paid in multiple currencies
        #         {                                       // if provided by exchange or calculated by ccxt
        #             'cost':  0.0015,                    // float
        #             'currency': 'ETH',                  // usually base currency for buys, quote currency for sells
        #             'rate': 0.002,                      // the fee rate (if available)
        #         },
        #     ],
        # }

        # Example:
        # {
        #     "id": "12345-67890",
        #     "timestamp": 1652376800000,
        #     "symbol": "BTC/USDT",
        #     "order": "12345-67890",
        #     "type": "limit",
        #     "side": "buy",
        #     "takerOrMaker": "taker",
        #     "price": 50000.0,
        #     "amount": 0.1,
        #     "cost": 5000.0,
        #     "fee": {
        #         "cost": 0.0015,
        #         "currency": "ETH",
        #         "rate": 0.002
        #     },
        #     "fees": [
        #         {
        #             "cost": 0.0015,
        #             "currency": "ETH",
        #             "rate": 0.002
        #         }
        #     ]
        # }
        # TODO try to use self.safe_trade
        fee, fees = self.parsed_fee_and_fees(trade)
        return {
            'id': self.safe_string(trade, 'id'),
            'symbol': self.safe_string(trade, 'symbol'),
            'timestamp': self.safe_integer(trade, 'timestamp'),
            'datetime': self.safe_string(trade, 'datetime'),
            'order': self.safe_string(trade, 'order'),
            'type': self.safe_string(trade, 'type'),
            'takerOrMaker': self.safe_string(trade, 'takerOrMaker'),
            'side': self.safe_string(trade, 'side'),
            'price': self.safe_float(trade, 'price'),
            'amount': self.safe_float(trade, 'amount'),
            'cost': self.safe_float(trade, 'cost'),
            'fee': fee,
            'fees': fees,
            'info': trade,
        }

    def fetch_trades(self, symbol: str, since: Int = None, limit: Int = None, params={}) -> List[Trade]:
        """
        get the list of most recent trades for a particular symbol
        :see: TODO add a link to the relevant part of the exchange API documentation
        :param str symbol: unified symbol of the market to fetch trades for
        :param int [since]: timestamp in ms of the earliest trade to fetch
        :param int [limit]: the maximum amount of trades to fetch
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns Trade[]: a list of `trade structures <https://docs.ccxt.com/#/?id=public-trades>`
        """
        request: dict = {
            'symbol': symbol,
        }
        if limit is not None:
            request['limit'] = limit
        if since is not None:
            request['since'] = since
        response = self.publicGetTrades(self.extend(request, params))
        # [
        #     {
        #         "id": "12345-67890",
        #         "timestamp": 1652376800000,
        #         "symbol": "BTC/USDT",
        #         "order": "12345-67890",
        #         "type": "limit",
        #         "side": "buy",
        #         "takerOrMaker": "taker",
        #         "price": 50000.0,
        #         "amount": 0.1,
        #         "cost": 5000.0,
        #         "fee": {
        #             "cost": 0.0015,
        #             "currency": "ETH",
        #             "rate": 0.002
        #         },
        #         "fees": [
        #             {
        #                 "cost": 0.0015,
        #                 "currency": "ETH",
        #                 "rate": 0.002
        #             }
        #         ]
        #     },
        #     {
        #         "id": "12345-67891",
        #         "timestamp": 1652376801000,
        #         "symbol": "BTC/USDT",
        #         "order": "12345-67891",
        #         "type": "limit",
        #         "side": "sell",
        #         "takerOrMaker": "maker",
        #         "price": 50000.0,
        #         "amount": 0.1,
        #         "cost": 5000.0,
        #         "fee": {
        #             "cost": 0.0015,
        #             "currency": "ETH",
        #             "rate": 0.002
        #         },
        #         "fees": [
        #             {
        #                 "cost": 0.0015,
        #                 "currency": "ETH",
        #                 "rate": 0.002
        #             }
        #         ]
        #     }
        # ]
        return self.parse_trades(response, None, since, limit)

    def fetch_my_trades(self, symbol: Str = None, since: Int = None, limit: Int = None, params={}) -> List[Trade]:
        # TODO temporary repeat method fetch_trades
        return self.fetch_trades(symbol, since, limit, params)

    def sign(self, path, api='public', method='GET', params={}, headers=None, body=None):
        endpoint = '/' + self.implode_params(path, params)
        url = self.implode_hostname(self.urls['api'][api])
        headers = headers if (headers is not None) else {}
        query = self.omit(params, self.extract_params(path))
        if query:
            if (method == 'GET') or (method == 'DELETE'):
                endpoint += '?' + self.urlencode(query)
            else:
                body = self.json(query)
                headers['Content-Type'] = 'application/json'
        url = url + endpoint
        return {'url': url, 'method': method, 'body': body, 'headers': headers}

    def handle_errors(self, httpCode: int, reason: str, url: str, method: str, headers: dict, body: str, response, requestHeaders, requestBody):
        if response is None:
            return None  # fallback to default error handler
        #
        #    {
        #        "code": 80014,
        #        "msg": "Invalid parameters, err:Key: 'GetTickerRequest.Symbol' Error:Field validation for "Symbol" failed on the "len=0|endswith=-USDT" tag",
        #        "data": {
        #        }
        #    }
        #
        code = self.safe_string(response, 'code')
        message = self.safe_string(response, 'msg')
        if code is not None and code != '0':
            feedback = self.id + ' ' + body
            self.throw_exactly_matched_exception(self.exceptions['exact'], message, feedback)
            self.throw_exactly_matched_exception(self.exceptions['exact'], code, feedback)
            self.throw_broadly_matched_exception(self.exceptions['broad'], message, feedback)
            raise ExchangeError(feedback)  # unknown message
        return None
