# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.base.exchange import Exchange
from ccxt.abstract.gains import ImplicitAPI
from ccxt.base.types import Balances, Int, LeverageTier, LeverageTiers, Market, Num, Order, OrderSide, OrderType, Str, Strings, Ticker, Trade
from typing import List
from ccxt.base.errors import ExchangeError
from ccxt.base.errors import AuthenticationError
from ccxt.base.errors import ArgumentsRequired
from ccxt.base.errors import BadRequest
from ccxt.base.errors import InsufficientFunds
from ccxt.base.errors import InvalidOrder
from ccxt.base.decimal_to_precision import TICK_SIZE


class gains(Exchange, ImplicitAPI):

    def describe(self):
        return self.deep_extend(super(gains, self).describe(), {
            'id': 'gains',
            'name': 'gains',
            'countries': ['EU'],
            'version': 'v1',
            'rateLimit': 10,
            'pro': False,
            'has': {
                'CORS': None,
                'spot': False,
                'margin': False,
                'swap': False,
                'future': False,
                'option': False,
                'cancelAllOrders': False,
                'cancelOrder': True,
                'cancelOrders': False,
                'closeAllPositions': False,
                'closePosition': False,
                'createOrder': True,
                'editOrder': False,
                'fetchBalance': True,
                'fetchBorrowRateHistories': False,
                'fetchBorrowRateHistory': False,
                'fetchClosedOrders': False,
                'fetchCrossBorrowRate': False,
                'fetchCrossBorrowRates': False,
                'fetchCurrencies': False,
                'fetchDepositAddress': False,
                'fetchDeposits': False,
                'fetchFundingHistory': False,
                'fetchFundingRate': False,
                'fetchFundingRateHistory': False,
                'fetchFundingRates': False,
                'fetchIndexOHLCV': False,
                'fetchIsolatedBorrowRate': False,
                'fetchIsolatedBorrowRates': False,
                'fetchLeverageTiers': True,
                'fetchMarginMode': False,
                'fetchMarkets': True,
                'fetchMarkOHLCV': False,
                'fetchMyTrades': False,
                'fetchOHLCV': True,
                'fetchOpenInterestHistory': False,
                'fetchOpenOrders': False,
                'fetchOrder': True,
                'fetchOrderBook': True,
                'fetchOrders': True,
                'fetchOrderTrades': False,
                'fetchPosition': False,
                'fetchPositionHistory': False,
                'fetchPositionMode': False,
                'fetchPositions': False,
                'fetchPositionsForSymbol': False,
                'fetchPositionsHistory': False,
                'fetchPositionsRisk': False,
                'fetchPremiumIndexOHLCV': False,
                'fetchTicker': True,
                'fetchTickers': False,
                'fetchTime': False,
                'fetchTrades': True,
                'fetchTradingFee': False,
                'fetchTradingFees': False,
                'fetchTransactionFees': False,
                'fetchTransactions': False,
                'fetchTransfer': False,
                'fetchTransfers': False,
                'fetchWithdrawal': False,
                'fetchWithdrawals': False,
                'setLeverage': True,
                'setMarginMode': False,
                'transfer': False,
                'withdraw': False,
                'ws': False,
            },
            # TODO: update self with real timeframes provided by gains if needed
            'timeframes': {
                '1m': 1,
                '5m': 5,
                '10m': 10,
                '30m': 10,
                '1h': 60,
                '2h': 120,
                '4h': 240,
                '8h': 480,
                '12h': 720,
                '1d': 24,
                '1w': 70,
                '1M': 31,
            },
            # TODO: update self with real URLs provided by gains
            'urls': {
                'logo': 'https://some-logo.jpg',
                'api': {
                    'public': 'http://127.0.0.1:8000',
                    'private': 'http://127.0.0.1:8000',
                },
                'www': 'https://gains.com/',
                'doc': [
                    'https://gains.com/gains-offical-api-docs',
                ],
                'fees': 'https://gains.com/fees',
            },
            # TODO: update self with real credentials keys provided by gains
            'requiredCredentials': {
                'apiKey': True,
                'secret': True,
            },
            'api': {
                'public': {
                    'get': [
                        'markets',
                        'ohlcv',
                        'ticker',
                        'trades',
                    ],
                },
                'private': {
                    'get': [
                        'orders',
                        'order',
                        'balance',
                        'leverage_tiers',
                    ],
                    'post': [
                        'order',
                        'leverage',
                    ],
                    'delete': [
                        'order',
                    ],
                },
            },
            # TODO: update self with real fees provided by gains
            'fees': {
            },
            'options': {
            },
            'precisionMode': TICK_SIZE,
            # TODO: update self with real exceptions provided by gains
            'exceptions': {
                'exact': {
                    '2003': InvalidOrder,
                    '2004': InvalidOrder,
                    '2005': InvalidOrder,
                    '2021': InsufficientFunds,
                    '2036': InvalidOrder,
                    '2039': InvalidOrder,
                    '2053': InvalidOrder,
                    '2061': BadRequest,
                    '2063': InvalidOrder,
                    '9996': BadRequest,
                    '10012': AuthenticationError,
                    '20182': AuthenticationError,
                    '20183': InvalidOrder,
                },
                'broad': {
                },
            },
            'commonCurrencies': {
            },
        })

    def fetch_markets(self, params={}) -> List[Market]:
        """
        retrieves data on all markets for gains
        :see: TODO add a link to the relevant part of the exchange API documentation
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict[]: an array of objects representing market data
        """
        response = self.publicGetMarkets(params)
        # [
        #     {
        #         "id": "BTC/USDT",
        #         "symbol": "BTC/USDT",
        #         "base": "BTC",
        #         "quote": "USDT",
        #         "baseId": "btc",
        #         "quoteId": "usdt"
        #     },
        #     {
        #         "id": "ETH/USDT",
        #         "symbol": "ETH/USDT",
        #         "base": "ETH",
        #         "quote": "USDT",
        #         "baseId": "eth",
        #         "quoteId": "usdt"
        #     }
        # ]
        return self.parse_markets(response)

    def parse_market(self, market: dict) -> Market:
        # {
        #     "id": "BTC/USDT",
        #     "symbol": "BTC/USDT",
        #     "base": "BTC",
        #     "quote": "USDT",
        #     "baseId": "btc",
        #     "quoteId": "usdt"
        # }
        return {
            'id': self.safe_string(market, 'id'),
            'uppercaseId': None,
            'symbol': self.safe_string(market, 'symbol'),
            'base': self.safe_string(market, 'base'),
            'baseId': self.safe_string(market, 'baseId'),
            'quote': self.safe_string(market, 'quote'),
            'quoteId': self.safe_string(market, 'quoteId'),
            'settle': None,
            'settleId': None,
            'type': 'swap',
            'spot': False,
            'margin': False,
            'swap': True,
            'future': False,
            'option': False,
            'contract': self.safe_bool(market, 'contract', True),
            'linear': None,
            'inverse': None,
            'contractSize': None,
            'expiry': None,
            'expiryDatetime': None,
            'strike': None,
            'optionType': None,
            'limits': {
                'amount': {
                    'min': 0.1,
                    'max': 480286,
                },
                'price': {
                    'min': None,
                    'max': None,
                },
                'cost': {
                    'min': None,
                    'max': None,
                },
                'leverage': {
                    'min': None,
                    'max': None,
                },
            },
            'precision': {
                'price': 100,
                'amount': 1,
            },
            'active': None,
            'created': None,
            'info': market,
        }

    def parse_order(self, order: dict, market: Market = None) -> Order:
        # {
        #     "id": "12345-67890",
        #     "timestamp": 1652376800000,
        #     "status": "open",
        #     "symbol": "BTC/USDT",
        #     "type": "limit",
        #     "side": "buy",
        #     "price": 50000.0,
        #     "amount": 0.1,
        #     "filled": 0.0,
        #     "remaining": 0.1,
        #     "cost": 0.0,
        #     "fee": {
        #         "currency": "BTC",
        #         "cost": 0.0009,
        #         "rate": 0.002
        #     }
        # }
        timestamp: Int = self.safe_integer(order, 'timestamp', None)
        return self.safe_order({
            'id': self.safe_string(order, 'id'),
            'clientOrderId': None,
            'timestamp': self.safe_integer(order, 'timestamp', None),
            'datetime': self.iso8601(timestamp),
            'lastTradeTimestamp': None,
            'symbol': self.safe_string(order, 'symbol', None),
            'type': self.safe_string(order, 'type', None),
            'timeInForce': None,
            'postOnly': None,
            'side': self.safe_string(order, 'side', None),
            'price': self.safe_float(order, 'price', None),
            'stopPrice': None,
            'amount': self.safe_float(order, 'amount', None),
            'cost': None,
            'average': self.safe_float(order, 'average', None),
            'filled': self.safe_float(order, 'filled', None),
            'remaining': self.safe_float(order, 'remaining', None),
            'status': self.safe_string(order, 'status', None),
            'fee': self.safe_dict(order, 'fee', {}),
            'trades': self.safe_list(order, 'trades', []),
            'info': order,
        }, market)

    def fetch_order(self, id: str, symbol: Str = None, params={}):
        """
        fetches information on an order made by the user
        :see: TODO add a link to the relevant part of the exchange API documentation
        :param str id: the order id
        :param str symbol: unified symbol of the market the order was made in
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: An `order structure <https://docs.ccxt.com/#/?id=order-structure>`
        """
        self.load_markets()
        market = self.market(symbol)
        request: dict = {
            'id': id,
            'pair': market['id'],
        }
        response = self.privateGetOrder(self.extend(request, params))
        # {
        #     "id": "12345-67890",
        #     "timestamp": 1652376800000,
        #     "status": "open",
        #     "symbol": "BTC/USDT",
        #     "type": "limit",
        #     "side": "buy",
        #     "price": 50000.0,
        #     "amount": 0.1,
        #     "filled": 0.0,
        #     "remaining": 0.1,
        #     "cost": 0.0,
        #     "fee": {
        #         "currency": "BTC",
        #         "cost": 0.0009,
        #         "rate": 0.002
        #     }
        # }
        return self.parse_order(response, None)

    def fetch_orders(self, symbol: Str = None, since: Int = None, limit: Int = None, params={}) -> List[Order]:
        """
        fetches information on multiple orders made by the user
        :see: TODO add a link to the relevant part of the exchange API documentation
        :param str symbol: unified market symbol of the market orders were made in
        :param int [since]: the earliest time in ms to fetch orders for
        :param int [limit]: the maximum number of order structures to retrieve
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns Order[]: a list of `order structures <https://docs.ccxt.com/#/?id=order-structure>`
        """
        if symbol is None:
            raise ArgumentsRequired(self.id + ' fetchOrders() requires a symbol argument')
        self.load_markets()
        market = self.market(symbol)
        request: dict = {
            'pair': market['id'],
        }
        if since is not None:
            request['since'] = since
        if limit is not None:
            request['limit'] = limit
        response = self.privateGetOrders(self.extend(request, params))
        # [
        #     {
        #         "id": "12345-67890",
        #         "timestamp": 1652376800000,
        #         "status": "open",
        #         "symbol": "BTC/USDT",
        #         "type": "limit",
        #         "side": "buy",
        #         "price": 50000.0,
        #         "amount": 0.1,
        #         "filled": 0.0,
        #         "remaining": 0.1,
        #         "cost": 0.0,
        #         "fee": {
        #             "currency": "BTC",
        #             "cost": 0.0009,
        #             "rate": 0.002
        #         }
        #     },
        #     {
        #         "id": "12345-67891",
        #         "timestamp": 1652376801000,
        #         "status": "closed",
        #         "symbol": "ETH/USDT",
        #         "type": "market",
        #         "side": "sell",
        #         "price": 4000.0,
        #         "amount": 1.0,
        #         "filled": 1.0,
        #         "remaining": 0.0,
        #         "cost": 4000.0,
        #         "fee": {
        #             "currency": "ETH",
        #             "cost": 0.004,
        #             "rate": 0.001
        #         }
        #     }
        # ]
        return self.parse_orders(response, market, since, limit)

    def create_order(self, symbol: str, type: OrderType, side: OrderSide, amount: float, price: Num = None, params={}):
        """
        create a trade order
        :see: TODO add a link to the relevant part of the exchange API documentation
        :param str symbol: unified symbol of the market to create an order in
        :param str type: 'market' or 'limit'
        :param str side: 'buy' or 'sell'
        :param float amount: how much of currency you want to trade in units of base currency
        :param float [price]: the price at which the order is to be fulfilled, in units of the quote currency, ignored in market orders
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: an `order structure <https://docs.ccxt.com/#/?id=order-structure>`
        """
        self.load_markets()
        market = self.market(symbol)
        request: dict = {
            'pair': market['id'],
            'type': type,
            'side': side,
            'amount': self.amount_to_precision(symbol, amount),
        }
        if type == 'limit':
            request['price'] = self.price_to_precision(symbol, price)
        response = self.privatePostOrder(self.extend(request, params))
        # {
        #     "id": "12345-67890",
        #     "timestamp": 1652376800000,
        #     "status": "open",
        #     "symbol": "BTC/USDT",
        #     "type": "limit",
        #     "side": "buy",
        #     "price": 50000.0,
        #     "amount": 0.1,
        #     "filled": 0.0,
        #     "remaining": 0.1,
        #     "cost": 0.0,
        #     "fee": {
        #         "currency": "BTC",
        #         "cost": 0.0009,
        #         "rate": 0.002
        #     }
        # }
        return self.parse_order(response, market)

    def cancel_order(self, id: str, symbol: Str = None, params={}):
        """
        cancels an open order
        :see: TODO add a link to the relevant part of the exchange API documentation
        :param str id: order id
        :param str symbol: unified symbol of the market the order was made in
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: An `order structure <https://docs.ccxt.com/#/?id=order-structure>`
        """
        self.load_markets()
        market = self.market(symbol)
        request: dict = {
            'id': id,
            'pair': market['id'],
        }
        response = self.privateDeleteOrder(self.extend(request, params))
        # {
        #     "id": "12345-67890",
        #     "timestamp": 1652376800000,
        #     "status": "canceled",
        #     "symbol": "BTC/USDT",
        #     "type": "limit",
        #     "side": "buy",
        #     "price": 50000.0,
        #     "amount": 0.1,
        #     "filled": 0.0,
        #     "remaining": 0.1,
        #     "cost": 0.0,
        #     "fee": {
        #         "currency": "BTC",
        #         "cost": 0.0009,
        #         "rate": 0.002
        #     }
        # }
        return self.parse_order(response, market)

    def parse_balance(self, balance) -> Balances:
        # {
        #     "timestamp": 1652376800000,
        #     "free": {
        #         "BTC": 0.1,
        #         "USD": 5000.0
        #     },
        #     "used": {
        #         "BTC": 0.0,
        #         "USD": 0.0
        #     },
        #     "total": {
        #         "BTC": 0.1,
        #         "USD": 5000.0
        #     },
        #     "debt": {
        #         "BTC": 0.0,
        #         "USD": 0.0
        #     }
        # }
        timestamp = self.safe_integer(balance, 'timestamp')
        return self.safe_balance({
            'info': balance,
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'free': self.safe_dict(balance, 'free', {}),
            'used': self.safe_dict(balance, 'used', {}),
            'total': self.safe_dict(balance, 'total', {}),
            'debt': self.safe_dict(balance, 'debt', {}),
        })

    def fetch_balance(self, params={}) -> Balances:
        """
        query for balance and get the amount of funds available for trading or funds locked in orders
        :see: TODO add a link to the relevant part of the exchange API documentation
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: a `balance structure <https://docs.ccxt.com/#/?id=balance-structure>`
        """
        self.load_markets()
        response = self.privateGetBalance(params)
        # {
        #     "timestamp": 1652376800000,
        #     "free": {
        #         "BTC": 0.1,
        #         "USD": 5000.0
        #     },
        #     "used": {
        #         "BTC": 0.0,
        #         "USD": 0.0
        #     },
        #     "total": {
        #         "BTC": 0.1,
        #         "USD": 5000.0
        #     },
        #     "debt": {
        #         "BTC": 0.0,
        #         "USD": 0.0
        #     }
        # }
        return self.parse_balance(response)

    def fetch_ohlcv(self, symbol: str, timeframe='1m', since: Int = None, limit: Int = None, params={}) -> List[list]:
        """
        fetches historical candlestick data containing the open, high, low, and close price, and the volume of a market
        :see: TODO add a link to the relevant part of the exchange API documentation
        :param str symbol: unified symbol of the market to fetch OHLCV data for
        :param str timeframe: the length of time each candle represents
        :param int [since]: timestamp in ms of the earliest candle to fetch
        :param int [limit]: the maximum amount of candles to fetch
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns int[][]: A list of candles ordered, open, high, low, close, volume
        """
        self.load_markets()
        market = self.market(symbol)
        request: dict = {
            'pair': market['id'],
            'timeframe': self.safe_string(self.timeframes, timeframe, timeframe),
        }
        if limit is not None:
            request['limit'] = limit
        if since is not None:
            request['since'] = since
        response = self.publicGetOhlcv(self.extend(request, params))
        # [
        #     [
        #         1504541580000,  # UTC timestamp in milliseconds, integer
        #         4235.4,         #(O)pen price, float
        #         4240.6,         #(H)ighest price, float
        #         4230.0,         #(L)owest price, float
        #         4230.7,         #(C)losing price, float
        #         37.72941911     #(V)olume float in base currency
        #     ],
        #     [
        #         1504541640000,
        #         4231.6,
        #         4240.7,
        #         4231.6,
        #         4236.2,
        #         61.46897393
        #     ]
        # ]
        return self.parse_ohlcvs(response, market, timeframe, since, limit)

    def parse_ticker(self, ticker: dict, market: Market = None) -> Ticker:
        # {
        #     "symbol": "BTC/USDT",
        #     "timestamp": 1652376800000,
        #     "high": 50000.0,
        #     "low": 49000.0,
        #     "bid": 49500.0,
        #     "bidVolume": 0.1,
        #     "ask": 50500.0,
        #     "askVolume": 0.1,
        #     "vwap": 50000.0,
        #     "open": 49000.0,
        #     "close": 50000.0,
        #     "previousClose": 49000.0,
        #     "baseVolume": 0.1,
        #     "quoteVolume": 5000.0
        # }
        marketId = self.safe_string(ticker, 'id')
        symbol = self.safe_symbol(marketId, market)
        timestamp = self.safe_integer_2(ticker, 'timestamp', 'timestamp')
        return self.safe_ticker({
            'symbol': symbol,
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'high': self.safe_string(ticker, 'high'),
            'low': self.safe_string(ticker, 'low'),
            'bid': self.safe_string(ticker, 'bid'),
            'bidVolume': self.safe_string(ticker, 'bid_volume'),
            'ask': self.safe_string(ticker, 'ask'),
            'askVolume': self.safe_string(ticker, 'askVolume'),
            'vwap': self.safe_string(ticker, 'vwap'),
            'open': self.safe_string(ticker, 'open'),
            'close': self.safe_string(ticker, 'close'),
            'last': None,
            'previousClose': self.safe_string(ticker, 'previousClose'),
            'change': None,
            'percentage': None,
            'average': None,
            'baseVolume': self.safe_string(ticker, 'baseVolume'),
            'quoteVolume': self.safe_string(ticker, 'quoteVolume'),
            'info': ticker,
        }, market)

    def fetch_ticker(self, symbol: str, params={}) -> Ticker:
        """
        fetches a price ticker, a statistical calculation with the information calculated over the past 24 hours for a specific market
        :see: TODO add a link to the relevant part of the exchange API documentation
        :param str symbol: unified symbol of the market to fetch the ticker for
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: a `ticker structure <https://docs.ccxt.com/#/?id=ticker-structure>`
        """
        self.load_markets()
        market = self.market(symbol)
        request: dict = {
            'pair': market['id'],
        }
        response = self.publicGetTicker(self.extend(request, params))
        # {
        #     "symbol": "BTC/USDT",
        #     "timestamp": 1652376800000,
        #     "high": 50000.0,
        #     "low": 49000.0,
        #     "bid": 49500.0,
        #     "bidVolume": 0.1,
        #     "ask": 50500.0,
        #     "askVolume": 0.1,
        #     "vwap": 50000.0,
        #     "open": 49000.0,
        #     "close": 50000.0,
        #     "previousClose": 49000.0,
        #     "baseVolume": 0.1,
        #     "quoteVolume": 5000.0
        # }
        return self.parse_ticker(response, market)

    def parse_market_leverage_tiers(self, info, market: Market = None) -> List[LeverageTier]:
        """
        :param dict info: Exchange response for 1 market
        :param dict market: CCXT market
        """
        # [
        #     {
        #         "tier": 1,
        #         "notionalCurrency": "USD",
        #         "minNotional": 10.0,
        #         "maxNotional": 100.0,
        #         "maintenanceMarginRate": 0.01,
        #         "maxLeverage": 10
        #     },
        #     {
        #         "tier": 2,
        #         "notionalCurrency": "USD",
        #         "minNotional": 100.0,
        #         "maxNotional": 1000.0,
        #         "maintenanceMarginRate": 0.02,
        #         "maxLeverage": 20
        #     }
        # ]
        results = []
        for j in range(0, len(info)):
            leverageTier = info[j]
            results.append({
                'tier': self.safe_number(leverageTier, 'tier'),
                'symbol': market['symbol'],
                'currency': self.safe_string(leverageTier, 'notionalCurrency'),
                'minNotional': self.safe_number(leverageTier, 'minNotional'),
                'maxNotional': self.safe_number(leverageTier, 'maxNotional'),
                'maintenanceMarginRate': self.safe_number(leverageTier, 'maintenanceMarginRate'),
                'maxLeverage': self.safe_number(leverageTier, 'maxLeverage'),
                'info': leverageTier,
            })
        return results

    def fetch_leverage_tiers(self, symbols: Strings = None, params={}) -> LeverageTiers:
        """
        :see: TODO add a link to the relevant part of the exchange API documentation
        retrieve information on the maximum leverage, and maintenance margin for trades of varying trade sizes
        :param str[]|None symbols: list of unified market symbols
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: a dictionary of `leverage tiers structures <https://docs.ccxt.com/#/?id=leverage-tiers-structure>`, indexed by market symbols
        """
        # {
        #     "BTC/USDT": [
        #         {
        #             "tier": 1,
        #             "notionalCurrency": "USD",
        #             "minNotional": 10.0,
        #             "maxNotional": 100.0,
        #             "maintenanceMarginRate": 0.01,
        #             "maxLeverage": 10
        #         },
        #         {
        #             "tier": 2,
        #             "notionalCurrency": "USD",
        #             "minNotional": 100.0,
        #             "maxNotional": 1000.0,
        #             "maintenanceMarginRate": 0.02,
        #             "maxLeverage": 20
        #         }
        #     ]
        # }
        self.load_markets()
        response = self.privateGetLeverageTiers(params)
        symbols = self.market_symbols(symbols)
        return self.parse_leverage_tiers(response, symbols, 'symbol')

    def set_leverage(self, leverage: Int, symbol: Str = None, params={}):
        """
        set the level of leverage for a market
        :see: TODO add a link to the relevant part of the exchange API documentation
        :param float leverage: the rate of leverage
        :param str symbol: unified market symbol
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: response from the exchange
        """
        if symbol is None:
            raise ArgumentsRequired(self.id + ' setLeverage() requires a symbol argument')
        self.load_markets()
        market = self.market(symbol)
        request: dict = {
            'pair': market['id'],
            'leverage': leverage,
        }
        return self.privatePostLeverage(self.extend(request, params))
        # {
        #     "symbol": "BTC/USDT",
        #     "longLeverage": 100,
        #     "shortLeverage": 75
        # }

    def parse_trade(self, trade: dict, market: Market = None) -> Trade:
        # {
        #     "id": "12345-67890",
        #     "timestamp": 1652376800000,
        #     "symbol": "BTC/USDT",
        #     "order": "12345-67890",
        #     "type": "limit",
        #     "side": "buy",
        #     "takerOrMaker": "taker",
        #     "price": 50000.0,
        #     "amount": 0.1,
        #     "cost": 5000.0,
        #     "fee": {
        #         "cost": 0.0015,
        #         "currency": "ETH",
        #         "rate": 0.002
        #     },
        #     "fees": [
        #         {
        #             "cost": 0.0015,
        #             "currency": "ETH",
        #             "rate": 0.002
        #         }
        #     ]
        # }
        timestamp = self.safe_integer(trade, 'timestamp')
        market = self.safe_market(None, market)
        return self.safe_trade({
            'id': self.safe_string(trade, 'id'),
            'symbol': market['symbol'],
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'order': self.safe_string(trade, 'order'),
            'type': self.safe_string(trade, 'type'),
            'takerOrMaker': self.safe_string(trade, 'takerOrMaker'),
            'side': self.safe_string(trade, 'side'),
            'price': self.safe_string(trade, 'price'),
            'amount': self.safe_string(trade, 'amount'),
            'cost': self.safe_string(trade, 'cost'),
            'fee': self.safe_dict(trade, 'fee', {}),
            'fees': self.safe_list(trade, 'fees', []),
        }, market)

    def fetch_trades(self, symbol: str, since: Int = None, limit: Int = None, params={}) -> List[Trade]:
        """
        get the list of most recent trades for a particular symbol
        :see: TODO add a link to the relevant part of the exchange API documentation
        :param str symbol: unified symbol of the market to fetch trades for
        :param int [since]: timestamp in ms of the earliest trade to fetch
        :param int [limit]: the maximum amount of trades to fetch
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns Trade[]: a list of `trade structures <https://docs.ccxt.com/#/?id=public-trades>`
        """
        self.load_markets()
        market = self.market(symbol)
        request: dict = {
            'symbol': market['id'],
        }
        if limit is not None:
            request['limit'] = limit
        if since is not None:
            request['since'] = since
        response = self.publicGetTrades(self.extend(request, params))
        # [
        #     {
        #         "id": "12345-67890",
        #         "timestamp": 1652376800000,
        #         "symbol": "BTC/USDT",
        #         "order": "12345-67890",
        #         "type": "limit",
        #         "side": "buy",
        #         "takerOrMaker": "taker",
        #         "price": 50000.0,
        #         "amount": 0.1,
        #         "cost": 5000.0,
        #         "fee": {
        #             "cost": 0.0015,
        #             "currency": "ETH",
        #             "rate": 0.002
        #         },
        #         "fees": [
        #             {
        #                 "cost": 0.0015,
        #                 "currency": "ETH",
        #                 "rate": 0.002
        #             }
        #         ]
        #     },
        #     {
        #         "id": "12345-67891",
        #         "timestamp": 1652376801000,
        #         "symbol": "BTC/USDT",
        #         "order": "12345-67891",
        #         "type": "limit",
        #         "side": "sell",
        #         "takerOrMaker": "maker",
        #         "price": 50000.0,
        #         "amount": 0.1,
        #         "cost": 5000.0,
        #         "fee": {
        #             "cost": 0.0015,
        #             "currency": "ETH",
        #             "rate": 0.002
        #         },
        #         "fees": [
        #             {
        #                 "cost": 0.0015,
        #                 "currency": "ETH",
        #                 "rate": 0.002
        #             }
        #         ]
        #     }
        # ]
        return self.parse_trades(response, market, since, limit)

    def sign(self, path, api='public', method='GET', params={}, headers=None, body=None):
        endpoint = '/' + self.implode_params(path, params)
        apiUrl = self.urls['api']
        url = self.implode_hostname(apiUrl[api])
        headers = headers if (headers is not None) else {}
        if api == 'private':
            self.check_required_credentials()
            # TODO replace TEST_API_KEY_HEADER and TEST_SECRET_KEY_HEADER with actual keys
            headers['TEST_API_KEY_HEADER'] = self.apiKey
            headers['TEST_SECRET_KEY_HEADER'] = self.secret
        query = self.omit(params, self.extract_params(path))
        if query:
            if (method == 'GET') or (method == 'DELETE'):
                endpoint += '?' + self.urlencode(query)
            else:
                body = self.json(query)
                headers['Content-Type'] = 'application/json'
        url = url + endpoint
        return {'url': url, 'method': method, 'body': body, 'headers': headers}

    def handle_errors(self, httpCode: int, reason: str, url: str, method: str, headers: dict, body: str, response, requestHeaders, requestBody):
        if response is None:
            return None  # fallback to default error handler
        #
        #    {
        #        "code": 80014,
        #        "msg": "Invalid parameters, err:Key: 'GetTickerRequest.Symbol' Error:Field validation for "Symbol" failed on the "len=0|endswith=-USDT" tag",
        #        "data": {
        #        }
        #    }
        #
        code = self.safe_string(response, 'code')
        message = self.safe_string(response, 'msg')
        if code is not None and code != '0':
            feedback = self.id + ' ' + body
            self.throw_exactly_matched_exception(self.exceptions['exact'], message, feedback)
            self.throw_exactly_matched_exception(self.exceptions['exact'], code, feedback)
            self.throw_broadly_matched_exception(self.exceptions['broad'], message, feedback)
            raise ExchangeError(feedback)  # unknown message
        return None
