<?php

namespace ccxt\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class gains extends \ccxt\Exchange {
    public function public_get_markets($params = array()) {
        return $this->request('markets', 'public', 'GET', $params, null, null, array());
    }
    public function public_get_ohlcv($params = array()) {
        return $this->request('ohlcv', 'public', 'GET', $params, null, null, array());
    }
    public function public_get_ticker($params = array()) {
        return $this->request('ticker', 'public', 'GET', $params, null, null, array());
    }
    public function public_get_trades($params = array()) {
        return $this->request('trades', 'public', 'GET', $params, null, null, array());
    }
    public function private_get_orders($params = array()) {
        return $this->request('orders', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_order($params = array()) {
        return $this->request('order', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_balance($params = array()) {
        return $this->request('balance', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_leverage_tiers($params = array()) {
        return $this->request('leverage_tiers', 'private', 'GET', $params, null, null, array());
    }
    public function private_post_order($params = array()) {
        return $this->request('order', 'private', 'POST', $params, null, null, array());
    }
    public function private_post_leverage($params = array()) {
        return $this->request('leverage', 'private', 'POST', $params, null, null, array());
    }
    public function private_delete_order($params = array()) {
        return $this->request('order', 'private', 'DELETE', $params, null, null, array());
    }
    public function publicGetMarkets($params = array()) {
        return $this->request('markets', 'public', 'GET', $params, null, null, array());
    }
    public function publicGetOhlcv($params = array()) {
        return $this->request('ohlcv', 'public', 'GET', $params, null, null, array());
    }
    public function publicGetTicker($params = array()) {
        return $this->request('ticker', 'public', 'GET', $params, null, null, array());
    }
    public function publicGetTrades($params = array()) {
        return $this->request('trades', 'public', 'GET', $params, null, null, array());
    }
    public function privateGetOrders($params = array()) {
        return $this->request('orders', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetOrder($params = array()) {
        return $this->request('order', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetBalance($params = array()) {
        return $this->request('balance', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetLeverageTiers($params = array()) {
        return $this->request('leverage_tiers', 'private', 'GET', $params, null, null, array());
    }
    public function privatePostOrder($params = array()) {
        return $this->request('order', 'private', 'POST', $params, null, null, array());
    }
    public function privatePostLeverage($params = array()) {
        return $this->request('leverage', 'private', 'POST', $params, null, null, array());
    }
    public function privateDeleteOrder($params = array()) {
        return $this->request('order', 'private', 'DELETE', $params, null, null, array());
    }
}
