<?php

namespace ccxt;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception; // a common import
use ccxt\abstract\gains as Exchange;

class gains extends Exchange {

    public function describe() {
        return $this->deep_extend(parent::describe(), array(
            'id' => 'gains',
            'name' => 'gains',
            'countries' => array( 'EU' ),
            'version' => 'v1',
            'rateLimit' => 10,
            'pro' => false,
            'has' => array(
                'CORS' => null,
                'spot' => false,
                'margin' => false,
                'swap' => false,
                'future' => false,
                'option' => false,
                'cancelAllOrders' => false,
                'cancelOrder' => true,
                'cancelOrders' => false,
                'closeAllPositions' => false,
                'closePosition' => false,
                'createOrder' => true,
                'editOrder' => false,
                'fetchBalance' => true,
                'fetchBorrowRateHistories' => false,
                'fetchBorrowRateHistory' => false,
                'fetchClosedOrders' => false,
                'fetchCrossBorrowRate' => false,
                'fetchCrossBorrowRates' => false,
                'fetchCurrencies' => false,
                'fetchDepositAddress' => false,
                'fetchDeposits' => false,
                'fetchFundingHistory' => false,
                'fetchFundingRate' => false,
                'fetchFundingRateHistory' => false,
                'fetchFundingRates' => false,
                'fetchIndexOHLCV' => false,
                'fetchIsolatedBorrowRate' => false,
                'fetchIsolatedBorrowRates' => false,
                'fetchLeverageTiers' => true,
                'fetchMarginMode' => false,
                'fetchMarkets' => true,
                'fetchMarkOHLCV' => false,
                'fetchMyTrades' => false,
                'fetchOHLCV' => true,
                'fetchOpenInterestHistory' => false,
                'fetchOpenOrders' => false,
                'fetchOrder' => true,
                'fetchOrderBook' => true,
                'fetchOrders' => true,
                'fetchOrderTrades' => false,
                'fetchPosition' => false,
                'fetchPositionHistory' => false,
                'fetchPositionMode' => false,
                'fetchPositions' => false,
                'fetchPositionsForSymbol' => false,
                'fetchPositionsHistory' => false,
                'fetchPositionsRisk' => false,
                'fetchPremiumIndexOHLCV' => false,
                'fetchTicker' => true,
                'fetchTickers' => false,
                'fetchTime' => false,
                'fetchTrades' => true,
                'fetchTradingFee' => false,
                'fetchTradingFees' => false,
                'fetchTransactionFees' => false,
                'fetchTransactions' => false,
                'fetchTransfer' => false,
                'fetchTransfers' => false,
                'fetchWithdrawal' => false,
                'fetchWithdrawals' => false,
                'setLeverage' => true,
                'setMarginMode' => false,
                'transfer' => false,
                'withdraw' => false,
                'ws' => false,
            ),
            // TODO => update this with real timeframes provided by gains if needed
            'timeframes' => array(
                '1m' => 1,
                '5m' => 5,
                '10m' => 10,
                '30m' => 10,
                '1h' => 60,
                '2h' => 120,
                '4h' => 240,
                '8h' => 480,
                '12h' => 720,
                '1d' => 24,
                '1w' => 70,
                '1M' => 31,
            ),
            // TODO => update this with real URLs provided by gains
            'urls' => array(
                'logo' => 'https://some-logo.jpg',
                'api' => array(
                    'public' => 'http://127.0.0.1:8000',
                    'private' => 'http://127.0.0.1:8000',
                ),
                'www' => 'https://gains.com/',
                'doc' => array(
                    'https://gains.com/gains-offical-api-docs',
                ),
                'fees' => 'https://gains.com/fees',
            ),
            // TODO => update this with real credentials keys provided by gains
            'requiredCredentials' => array(
                'apiKey' => true,
                'secret' => true,
            ),
            'api' => array(
                'public' => array(
                    'get' => array(
                        'markets',
                        'ohlcv',
                        'ticker',
                        'trades',
                    ),
                ),
                'private' => array(
                    'get' => array(
                        'orders',
                        'order',
                        'balance',
                        'leverage_tiers',
                    ),
                    'post' => array(
                        'order',
                        'leverage',
                    ),
                    'delete' => array(
                        'order',
                    ),
                ),
            ),
            // TODO => update this with real fees provided by gains
            'fees' => array(
            ),
            'options' => array(
            ),
            'precisionMode' => TICK_SIZE,
            // TODO => update this with real exceptions provided by gains
            'exceptions' => array(
                'exact' => array(
                    '2003' => '\\ccxt\\InvalidOrder',
                    '2004' => '\\ccxt\\InvalidOrder',
                    '2005' => '\\ccxt\\InvalidOrder',
                    '2021' => '\\ccxt\\InsufficientFunds',
                    '2036' => '\\ccxt\\InvalidOrder',
                    '2039' => '\\ccxt\\InvalidOrder',
                    '2053' => '\\ccxt\\InvalidOrder',
                    '2061' => '\\ccxt\\BadRequest',
                    '2063' => '\\ccxt\\InvalidOrder',
                    '9996' => '\\ccxt\\BadRequest',
                    '10012' => '\\ccxt\\AuthenticationError',
                    '20182' => '\\ccxt\\AuthenticationError',
                    '20183' => '\\ccxt\\InvalidOrder',
                ),
                'broad' => array(
                ),
            ),
            'commonCurrencies' => array(
            ),
        ));
    }

    public function fetch_markets($params = array ()): array {
        /**
         * retrieves data on all markets for gains
         * @see TODO add a link to the relevant part of the exchange API documentation
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {array[]} an array of objects representing market data
         */
        $response = $this->publicGetMarkets ($params);
        // array(
        //     array(
        //         "id" => "BTC/USDT",
        //         "symbol" => "BTC/USDT",
        //         "base" => "BTC",
        //         "quote" => "USDT",
        //         "baseId" => "btc",
        //         "quoteId" => "usdt"
        //     ),
        //     {
        //         "id" => "ETH/USDT",
        //         "symbol" => "ETH/USDT",
        //         "base" => "ETH",
        //         "quote" => "USDT",
        //         "baseId" => "eth",
        //         "quoteId" => "usdt"
        //     }
        // )
        return $this->parse_markets($response);
    }

    public function parse_market(array $market): array {
        // {
        //     "id" => "BTC/USDT",
        //     "symbol" => "BTC/USDT",
        //     "base" => "BTC",
        //     "quote" => "USDT",
        //     "baseId" => "btc",
        //     "quoteId" => "usdt"
        // }
        return array(
            'id' => $this->safe_string($market, 'id'),
            'uppercaseId' => null,
            'symbol' => $this->safe_string($market, 'symbol'),
            'base' => $this->safe_string($market, 'base'),
            'baseId' => $this->safe_string($market, 'baseId'),
            'quote' => $this->safe_string($market, 'quote'),
            'quoteId' => $this->safe_string($market, 'quoteId'),
            'settle' => null,
            'settleId' => null,
            'type' => 'swap',
            'spot' => false,
            'margin' => false,
            'swap' => true,
            'future' => false,
            'option' => false,
            'contract' => $this->safe_bool($market, 'contract', true),
            'linear' => null,
            'inverse' => null,
            'contractSize' => null,
            'expiry' => null,
            'expiryDatetime' => null,
            'strike' => null,
            'optionType' => null,
            'limits' => array(
                'amount' => array(
                    'min' => 0.1,
                    'max' => 480286,
                ),
                'price' => array(
                    'min' => null,
                    'max' => null,
                ),
                'cost' => array(
                    'min' => null,
                    'max' => null,
                ),
                'leverage' => array(
                    'min' => null,
                    'max' => null,
                ),
            ),
            'precision' => array(
                'price' => 100,
                'amount' => 1,
            ),
            'active' => null,
            'created' => null,
            'info' => $market,
        );
    }

    public function parse_order(array $order, ?array $market = null): array {
        // {
        //     "id" => "12345-67890",
        //     "timestamp" => 1652376800000,
        //     "status" => "open",
        //     "symbol" => "BTC/USDT",
        //     "type" => "limit",
        //     "side" => "buy",
        //     "price" => 50000.0,
        //     "amount" => 0.1,
        //     "filled" => 0.0,
        //     "remaining" => 0.1,
        //     "cost" => 0.0,
        //     "fee" => {
        //         "currency" => "BTC",
        //         "cost" => 0.0009,
        //         "rate" => 0.002
        //     }
        // }
        $timestamp = $this->safe_integer($order, 'timestamp', null);
        return $this->safe_order(array(
            'id' => $this->safe_string($order, 'id'),
            'clientOrderId' => null,
            'timestamp' => $this->safe_integer($order, 'timestamp', null),
            'datetime' => $this->iso8601($timestamp),
            'lastTradeTimestamp' => null,
            'symbol' => $this->safe_string($order, 'symbol', null),
            'type' => $this->safe_string($order, 'type', null),
            'timeInForce' => null,
            'postOnly' => null,
            'side' => $this->safe_string($order, 'side', null),
            'price' => $this->safe_float($order, 'price', null),
            'stopPrice' => null,
            'amount' => $this->safe_float($order, 'amount', null),
            'cost' => null,
            'average' => $this->safe_float($order, 'average', null),
            'filled' => $this->safe_float($order, 'filled', null),
            'remaining' => $this->safe_float($order, 'remaining', null),
            'status' => $this->safe_string($order, 'status', null),
            'fee' => $this->safe_dict($order, 'fee', array()),
            'trades' => $this->safe_list($order, 'trades', array()),
            'info' => $order,
        ), $market);
    }

    public function fetch_order(string $id, ?string $symbol = null, $params = array ()) {
        /**
         * fetches information on an order made by the user
         * @see TODO add a link to the relevant part of the exchange API documentation
         * @param {string} $id the order $id
         * @param {string} $symbol unified $symbol of the $market the order was made in
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {array} An ~@link https://docs.ccxt.com/#/?$id=order-structure order structure~
         */
        $this->load_markets();
        $market = $this->market($symbol);
        $request = array(
            'id' => $id,
            'pair' => $market['id'],
        );
        $response = $this->privateGetOrder ($this->extend($request, $params));
        // {
        //     "id" => "12345-67890",
        //     "timestamp" => 1652376800000,
        //     "status" => "open",
        //     "symbol" => "BTC/USDT",
        //     "type" => "limit",
        //     "side" => "buy",
        //     "price" => 50000.0,
        //     "amount" => 0.1,
        //     "filled" => 0.0,
        //     "remaining" => 0.1,
        //     "cost" => 0.0,
        //     "fee" => {
        //         "currency" => "BTC",
        //         "cost" => 0.0009,
        //         "rate" => 0.002
        //     }
        // }
        return $this->parse_order($response, null);
    }

    public function fetch_orders(?string $symbol = null, ?int $since = null, ?int $limit = null, $params = array ()): array {
        /**
         * fetches information on multiple orders made by the user
         * @see TODO add a link to the relevant part of the exchange API documentation
         * @param {string} $symbol unified $market $symbol of the $market orders were made in
         * @param {int} [$since] the earliest time in ms to fetch orders for
         * @param {int} [$limit] the maximum number of order structures to retrieve
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {Order[]} a list of ~@link https://docs.ccxt.com/#/?id=order-structure order structures~
         */
        if ($symbol === null) {
            throw new ArgumentsRequired($this->id . ' fetchOrders() requires a $symbol argument');
        }
        $this->load_markets();
        $market = $this->market($symbol);
        $request = array(
            'pair' => $market['id'],
        );
        if ($since !== null) {
            $request['since'] = $since;
        }
        if ($limit !== null) {
            $request['limit'] = $limit;
        }
        $response = $this->privateGetOrders ($this->extend($request, $params));
        // array(
        //     {
        //         "id" => "12345-67890",
        //         "timestamp" => 1652376800000,
        //         "status" => "open",
        //         "symbol" => "BTC/USDT",
        //         "type" => "limit",
        //         "side" => "buy",
        //         "price" => 50000.0,
        //         "amount" => 0.1,
        //         "filled" => 0.0,
        //         "remaining" => 0.1,
        //         "cost" => 0.0,
        //         "fee" => array(
        //             "currency" => "BTC",
        //             "cost" => 0.0009,
        //             "rate" => 0.002
        //         }
        //     ),
        //     {
        //         "id" => "12345-67891",
        //         "timestamp" => 1652376801000,
        //         "status" => "closed",
        //         "symbol" => "ETH/USDT",
        //         "type" => "market",
        //         "side" => "sell",
        //         "price" => 4000.0,
        //         "amount" => 1.0,
        //         "filled" => 1.0,
        //         "remaining" => 0.0,
        //         "cost" => 4000.0,
        //         "fee" => {
        //             "currency" => "ETH",
        //             "cost" => 0.004,
        //             "rate" => 0.001
        //         }
        //     }
        // )
        return $this->parse_orders($response, $market, $since, $limit);
    }

    public function create_order(string $symbol, string $type, string $side, float $amount, ?float $price = null, $params = array ()) {
        /**
         * create a trade order
         * @see TODO add a link to the relevant part of the exchange API documentation
         * @param {string} $symbol unified $symbol of the $market to create an order in
         * @param {string} $type 'market' or 'limit'
         * @param {string} $side 'buy' or 'sell'
         * @param {float} $amount how much of currency you want to trade in units of base currency
         * @param {float} [$price] the $price at which the order is to be fulfilled, in units of the quote currency, ignored in $market orders
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {array} an ~@link https://docs.ccxt.com/#/?id=order-structure order structure~
         */
        $this->load_markets();
        $market = $this->market($symbol);
        $request = array(
            'pair' => $market['id'],
            'type' => $type,
            'side' => $side,
            'amount' => $this->amount_to_precision($symbol, $amount),
        );
        if ($type === 'limit') {
            $request['price'] = $this->price_to_precision($symbol, $price);
        }
        $response = $this->privatePostOrder ($this->extend($request, $params));
        // {
        //     "id" => "12345-67890",
        //     "timestamp" => 1652376800000,
        //     "status" => "open",
        //     "symbol" => "BTC/USDT",
        //     "type" => "limit",
        //     "side" => "buy",
        //     "price" => 50000.0,
        //     "amount" => 0.1,
        //     "filled" => 0.0,
        //     "remaining" => 0.1,
        //     "cost" => 0.0,
        //     "fee" => {
        //         "currency" => "BTC",
        //         "cost" => 0.0009,
        //         "rate" => 0.002
        //     }
        // }
        return $this->parse_order($response, $market);
    }

    public function cancel_order(string $id, ?string $symbol = null, $params = array ()) {
        /**
         * cancels an open order
         * @see TODO add a link to the relevant part of the exchange API documentation
         * @param {string} $id order $id
         * @param {string} $symbol unified $symbol of the $market the order was made in
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {array} An ~@link https://docs.ccxt.com/#/?$id=order-structure order structure~
         */
        $this->load_markets();
        $market = $this->market($symbol);
        $request = array(
            'id' => $id,
            'pair' => $market['id'],
        );
        $response = $this->privateDeleteOrder ($this->extend($request, $params));
        // {
        //     "id" => "12345-67890",
        //     "timestamp" => 1652376800000,
        //     "status" => "canceled",
        //     "symbol" => "BTC/USDT",
        //     "type" => "limit",
        //     "side" => "buy",
        //     "price" => 50000.0,
        //     "amount" => 0.1,
        //     "filled" => 0.0,
        //     "remaining" => 0.1,
        //     "cost" => 0.0,
        //     "fee" => {
        //         "currency" => "BTC",
        //         "cost" => 0.0009,
        //         "rate" => 0.002
        //     }
        // }
        return $this->parse_order($response, $market);
    }

    public function parse_balance($balance): array {
        // {
        //     "timestamp" => 1652376800000,
        //     "free" => array(
        //         "BTC" => 0.1,
        //         "USD" => 5000.0
        //     ),
        //     "used" => array(
        //         "BTC" => 0.0,
        //         "USD" => 0.0
        //     ),
        //     "total" => array(
        //         "BTC" => 0.1,
        //         "USD" => 5000.0
        //     ),
        //     "debt" => {
        //         "BTC" => 0.0,
        //         "USD" => 0.0
        //     }
        // }
        $timestamp = $this->safe_integer($balance, 'timestamp');
        return $this->safe_balance(array(
            'info' => $balance,
            'timestamp' => $timestamp,
            'datetime' => $this->iso8601($timestamp),
            'free' => $this->safe_dict($balance, 'free', array()),
            'used' => $this->safe_dict($balance, 'used', array()),
            'total' => $this->safe_dict($balance, 'total', array()),
            'debt' => $this->safe_dict($balance, 'debt', array()),
        ));
    }

    public function fetch_balance($params = array ()): array {
        /**
         * query for balance and get the amount of funds available for trading or funds locked in orders
         * @see TODO add a link to the relevant part of the exchange API documentation
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {array} a ~@link https://docs.ccxt.com/#/?id=balance-structure balance structure~
         */
        $this->load_markets();
        $response = $this->privateGetBalance ($params);
        // {
        //     "timestamp" => 1652376800000,
        //     "free" => array(
        //         "BTC" => 0.1,
        //         "USD" => 5000.0
        //     ),
        //     "used" => array(
        //         "BTC" => 0.0,
        //         "USD" => 0.0
        //     ),
        //     "total" => array(
        //         "BTC" => 0.1,
        //         "USD" => 5000.0
        //     ),
        //     "debt" => {
        //         "BTC" => 0.0,
        //         "USD" => 0.0
        //     }
        // }
        return $this->parse_balance($response);
    }

    public function fetch_ohlcv(string $symbol, $timeframe = '1m', ?int $since = null, ?int $limit = null, $params = array ()): array {
        /**
         * fetches historical candlestick data containing the open, high, low, and close price, and the volume of a $market
         * @see TODO add a link to the relevant part of the exchange API documentation
         * @param {string} $symbol unified $symbol of the $market to fetch OHLCV data for
         * @param {string} $timeframe the length of time each candle represents
         * @param {int} [$since] timestamp in ms of the earliest candle to fetch
         * @param {int} [$limit] the maximum amount of candles to fetch
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {int[][]} A list of candles ordered, open, high, low, close, volume
         */
        $this->load_markets();
        $market = $this->market($symbol);
        $request = array(
            'pair' => $market['id'],
            'timeframe' => $this->safe_string($this->timeframes, $timeframe, $timeframe),
        );
        if ($limit !== null) {
            $request['limit'] = $limit;
        }
        if ($since !== null) {
            $request['since'] = $since;
        }
        $response = $this->publicGetOhlcv ($this->extend($request, $params));
        // array(
        //     array(
        //         1504541580000,  // UTC timestamp in milliseconds, integer
        //         4235.4,         // (O)pen price, float
        //         4240.6,         // (H)ighest price, float
        //         4230.0,         // (L)owest price, float
        //         4230.7,         // (C)losing price, float
        //         37.72941911     // (V)olume float in base currency
        //     ),
        //     array(
        //         1504541640000,
        //         4231.6,
        //         4240.7,
        //         4231.6,
        //         4236.2,
        //         61.46897393
        //     )
        // )
        return $this->parse_ohlcvs($response, $market, $timeframe, $since, $limit);
    }

    public function parse_ticker(array $ticker, ?array $market = null): array {
        // {
        //     "symbol" => "BTC/USDT",
        //     "timestamp" => 1652376800000,
        //     "high" => 50000.0,
        //     "low" => 49000.0,
        //     "bid" => 49500.0,
        //     "bidVolume" => 0.1,
        //     "ask" => 50500.0,
        //     "askVolume" => 0.1,
        //     "vwap" => 50000.0,
        //     "open" => 49000.0,
        //     "close" => 50000.0,
        //     "previousClose" => 49000.0,
        //     "baseVolume" => 0.1,
        //     "quoteVolume" => 5000.0
        // }
        $marketId = $this->safe_string($ticker, 'id');
        $symbol = $this->safe_symbol($marketId, $market);
        $timestamp = $this->safe_integer_2($ticker, 'timestamp', 'timestamp');
        return $this->safe_ticker(array(
            'symbol' => $symbol,
            'timestamp' => $timestamp,
            'datetime' => $this->iso8601($timestamp),
            'high' => $this->safe_string($ticker, 'high'),
            'low' => $this->safe_string($ticker, 'low'),
            'bid' => $this->safe_string($ticker, 'bid'),
            'bidVolume' => $this->safe_string($ticker, 'bid_volume'),
            'ask' => $this->safe_string($ticker, 'ask'),
            'askVolume' => $this->safe_string($ticker, 'askVolume'),
            'vwap' => $this->safe_string($ticker, 'vwap'),
            'open' => $this->safe_string($ticker, 'open'),
            'close' => $this->safe_string($ticker, 'close'),
            'last' => null,
            'previousClose' => $this->safe_string($ticker, 'previousClose'),
            'change' => null,
            'percentage' => null,
            'average' => null,
            'baseVolume' => $this->safe_string($ticker, 'baseVolume'),
            'quoteVolume' => $this->safe_string($ticker, 'quoteVolume'),
            'info' => $ticker,
        ), $market);
    }

    public function fetch_ticker(string $symbol, $params = array ()): array {
        /**
         * fetches a price ticker, a statistical calculation with the information calculated over the past 24 hours for a specific $market
         * @see TODO add a link to the relevant part of the exchange API documentation
         * @param {string} $symbol unified $symbol of the $market to fetch the ticker for
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {array} a ~@link https://docs.ccxt.com/#/?id=ticker-structure ticker structure~
         */
        $this->load_markets();
        $market = $this->market($symbol);
        $request = array(
            'pair' => $market['id'],
        );
        $response = $this->publicGetTicker ($this->extend($request, $params));
        // {
        //     "symbol" => "BTC/USDT",
        //     "timestamp" => 1652376800000,
        //     "high" => 50000.0,
        //     "low" => 49000.0,
        //     "bid" => 49500.0,
        //     "bidVolume" => 0.1,
        //     "ask" => 50500.0,
        //     "askVolume" => 0.1,
        //     "vwap" => 50000.0,
        //     "open" => 49000.0,
        //     "close" => 50000.0,
        //     "previousClose" => 49000.0,
        //     "baseVolume" => 0.1,
        //     "quoteVolume" => 5000.0
        // }
        return $this->parse_ticker($response, $market);
    }

    public function parse_market_leverage_tiers($info, ?array $market = null): array {
        /**
         * @param {array} $info Exchange response for 1 $market
         * @param {array} $market CCXT $market
         */
        // array(
        //     array(
        //         "tier" => 1,
        //         "notionalCurrency" => "USD",
        //         "minNotional" => 10.0,
        //         "maxNotional" => 100.0,
        //         "maintenanceMarginRate" => 0.01,
        //         "maxLeverage" => 10
        //     ),
        //     {
        //         "tier" => 2,
        //         "notionalCurrency" => "USD",
        //         "minNotional" => 100.0,
        //         "maxNotional" => 1000.0,
        //         "maintenanceMarginRate" => 0.02,
        //         "maxLeverage" => 20
        //     }
        // )
        $results = array();
        for ($j = 0; $j < count($info); $j++) {
            $leverageTier = $info[$j];
            $results[] = array(
                'tier' => $this->safe_number($leverageTier, 'tier'),
                'symbol' => $market['symbol'],
                'currency' => $this->safe_string($leverageTier, 'notionalCurrency'),
                'minNotional' => $this->safe_number($leverageTier, 'minNotional'),
                'maxNotional' => $this->safe_number($leverageTier, 'maxNotional'),
                'maintenanceMarginRate' => $this->safe_number($leverageTier, 'maintenanceMarginRate'),
                'maxLeverage' => $this->safe_number($leverageTier, 'maxLeverage'),
                'info' => $leverageTier,
            );
        }
        return $results;
    }

    public function fetch_leverage_tiers(?array $symbols = null, $params = array ()): array {
        /**
         * @see TODO add a link to the relevant part of the exchange API documentation
         * retrieve information on the maximum leverage, and maintenance margin for trades of varying trade sizes
         * @param {string[]|null} $symbols list of unified market $symbols
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {array} a dictionary of ~@link https://docs.ccxt.com/#/?id=leverage-tiers-structure leverage tiers structures~, indexed by market $symbols
         */
        // {
        //     "BTC/USDT" => array(
        //         array(
        //             "tier" => 1,
        //             "notionalCurrency" => "USD",
        //             "minNotional" => 10.0,
        //             "maxNotional" => 100.0,
        //             "maintenanceMarginRate" => 0.01,
        //             "maxLeverage" => 10
        //         ),
        //         {
        //             "tier" => 2,
        //             "notionalCurrency" => "USD",
        //             "minNotional" => 100.0,
        //             "maxNotional" => 1000.0,
        //             "maintenanceMarginRate" => 0.02,
        //             "maxLeverage" => 20
        //         }
        //     )
        // }
        $this->load_markets();
        $response = $this->privateGetLeverageTiers ($params);
        $symbols = $this->market_symbols($symbols);
        return $this->parse_leverage_tiers($response, $symbols, 'symbol');
    }

    public function set_leverage(?int $leverage, ?string $symbol = null, $params = array ()) {
        /**
         * set the level of $leverage for a $market
         * @see TODO add a link to the relevant part of the exchange API documentation
         * @param {float} $leverage the rate of $leverage
         * @param {string} $symbol unified $market $symbol
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {array} response from the exchange
         */
        if ($symbol === null) {
            throw new ArgumentsRequired($this->id . ' setLeverage() requires a $symbol argument');
        }
        $this->load_markets();
        $market = $this->market($symbol);
        $request = array(
            'pair' => $market['id'],
            'leverage' => $leverage,
        );
        return $this->privatePostLeverage ($this->extend($request, $params));
        // {
        //     "symbol" => "BTC/USDT",
        //     "longLeverage" => 100,
        //     "shortLeverage" => 75
        // }
    }

    public function parse_trade(array $trade, ?array $market = null): array {
        // {
        //     "id" => "12345-67890",
        //     "timestamp" => 1652376800000,
        //     "symbol" => "BTC/USDT",
        //     "order" => "12345-67890",
        //     "type" => "limit",
        //     "side" => "buy",
        //     "takerOrMaker" => "taker",
        //     "price" => 50000.0,
        //     "amount" => 0.1,
        //     "cost" => 5000.0,
        //     "fee" => array(
        //         "cost" => 0.0015,
        //         "currency" => "ETH",
        //         "rate" => 0.002
        //     ),
        //     "fees" => array(
        //         {
        //             "cost" => 0.0015,
        //             "currency" => "ETH",
        //             "rate" => 0.002
        //         }
        //     )
        // }
        $timestamp = $this->safe_integer($trade, 'timestamp');
        $market = $this->safe_market(null, $market);
        return $this->safe_trade(array(
            'id' => $this->safe_string($trade, 'id'),
            'symbol' => $market['symbol'],
            'timestamp' => $timestamp,
            'datetime' => $this->iso8601($timestamp),
            'order' => $this->safe_string($trade, 'order'),
            'type' => $this->safe_string($trade, 'type'),
            'takerOrMaker' => $this->safe_string($trade, 'takerOrMaker'),
            'side' => $this->safe_string($trade, 'side'),
            'price' => $this->safe_string($trade, 'price'),
            'amount' => $this->safe_string($trade, 'amount'),
            'cost' => $this->safe_string($trade, 'cost'),
            'fee' => $this->safe_dict($trade, 'fee', array()),
            'fees' => $this->safe_list($trade, 'fees', array()),
        ), $market);
    }

    public function fetch_trades(string $symbol, ?int $since = null, ?int $limit = null, $params = array ()): array {
        /**
         * get the list of most recent trades for a particular $symbol
         * @see TODO add a link to the relevant part of the exchange API documentation
         * @param {string} $symbol unified $symbol of the $market to fetch trades for
         * @param {int} [$since] timestamp in ms of the earliest trade to fetch
         * @param {int} [$limit] the maximum amount of trades to fetch
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {Trade[]} a list of ~@link https://docs.ccxt.com/#/?id=public-trades trade structures~
         */
        $this->load_markets();
        $market = $this->market($symbol);
        $request = array(
            'symbol' => $market['id'],
        );
        if ($limit !== null) {
            $request['limit'] = $limit;
        }
        if ($since !== null) {
            $request['since'] = $since;
        }
        $response = $this->publicGetTrades ($this->extend($request, $params));
        // array(
        //     {
        //         "id" => "12345-67890",
        //         "timestamp" => 1652376800000,
        //         "symbol" => "BTC/USDT",
        //         "order" => "12345-67890",
        //         "type" => "limit",
        //         "side" => "buy",
        //         "takerOrMaker" => "taker",
        //         "price" => 50000.0,
        //         "amount" => 0.1,
        //         "cost" => 5000.0,
        //         "fee" => array(
        //             "cost" => 0.0015,
        //             "currency" => "ETH",
        //             "rate" => 0.002
        //         ),
        //         "fees" => array(
        //             array(
        //                 "cost" => 0.0015,
        //                 "currency" => "ETH",
        //                 "rate" => 0.002
        //             }
        //         )
        //     ),
        //     {
        //         "id" => "12345-67891",
        //         "timestamp" => 1652376801000,
        //         "symbol" => "BTC/USDT",
        //         "order" => "12345-67891",
        //         "type" => "limit",
        //         "side" => "sell",
        //         "takerOrMaker" => "maker",
        //         "price" => 50000.0,
        //         "amount" => 0.1,
        //         "cost" => 5000.0,
        //         "fee" => array(
        //             "cost" => 0.0015,
        //             "currency" => "ETH",
        //             "rate" => 0.002
        //         ),
        //         "fees" => array(
        //             {
        //                 "cost" => 0.0015,
        //                 "currency" => "ETH",
        //                 "rate" => 0.002
        //             }
        //         )
        //     }
        // )
        return $this->parse_trades($response, $market, $since, $limit);
    }

    public function sign($path, $api = 'public', $method = 'GET', $params = array (), $headers = null, $body = null) {
        $endpoint = '/' . $this->implode_params($path, $params);
        $apiUrl = $this->urls['api'];
        $url = $this->implode_hostname($apiUrl[$api]);
        $headers = ($headers !== null) ? $headers : array();
        if ($api === 'private') {
            $this->check_required_credentials();
            // TODO replace TEST_API_KEY_HEADER and TEST_SECRET_KEY_HEADER with actual keys
            $headers['TEST_API_KEY_HEADER'] = $this->apiKey;
            $headers['TEST_SECRET_KEY_HEADER'] = $this->secret;
        }
        $query = $this->omit($params, $this->extract_params($path));
        if ($query) {
            if (($method === 'GET') || ($method === 'DELETE')) {
                $endpoint .= '?' . $this->urlencode($query);
            } else {
                $body = $this->json($query);
                $headers['Content-Type'] = 'application/json';
            }
        }
        $url = $url . $endpoint;
        return array( 'url' => $url, 'method' => $method, 'body' => $body, 'headers' => $headers );
    }

    public function handle_errors(int $httpCode, string $reason, string $url, string $method, array $headers, string $body, $response, $requestHeaders, $requestBody) {
        if ($response === null) {
            return null; // fallback to default error handler
        }
        //
        //    {
        //        "code" => 80014,
        //        "msg" => "Invalid parameters, err:Key => 'GetTickerRequest.Symbol' Error:Field validation for "Symbol" failed on the "len=0|endswith=-USDT" tag",
        //        "data" => {
        //        }
        //    }
        //
        $code = $this->safe_string($response, 'code');
        $message = $this->safe_string($response, 'msg');
        if ($code !== null && $code !== '0') {
            $feedback = $this->id . ' ' . $body;
            $this->throw_exactly_matched_exception($this->exceptions['exact'], $message, $feedback);
            $this->throw_exactly_matched_exception($this->exceptions['exact'], $code, $feedback);
            $this->throw_broadly_matched_exception($this->exceptions['broad'], $message, $feedback);
            throw new ExchangeError($feedback); // unknown $message
        }
        return null;
    }
}
